// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wx-miniprogram/mgnt.proto

package wx_miniprogram // import "github.com/dev-openapi/wx-miniprogram"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClearQuotaData struct {
	Appid                string   `protobuf:"bytes,1,opt,name=appid" json:"appid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearQuotaData) Reset()         { *m = ClearQuotaData{} }
func (m *ClearQuotaData) String() string { return proto.CompactTextString(m) }
func (*ClearQuotaData) ProtoMessage()    {}
func (*ClearQuotaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_mgnt_78df39357633d749, []int{0}
}
func (m *ClearQuotaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearQuotaData.Unmarshal(m, b)
}
func (m *ClearQuotaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearQuotaData.Marshal(b, m, deterministic)
}
func (dst *ClearQuotaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearQuotaData.Merge(dst, src)
}
func (m *ClearQuotaData) XXX_Size() int {
	return xxx_messageInfo_ClearQuotaData.Size(m)
}
func (m *ClearQuotaData) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearQuotaData.DiscardUnknown(m)
}

var xxx_messageInfo_ClearQuotaData proto.InternalMessageInfo

func (m *ClearQuotaData) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

type ClearQuotaReq struct {
	AccessToken          string              `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	Body                 *ClearQuotaReq_Body `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ClearQuotaReq) Reset()         { *m = ClearQuotaReq{} }
func (m *ClearQuotaReq) String() string { return proto.CompactTextString(m) }
func (*ClearQuotaReq) ProtoMessage()    {}
func (*ClearQuotaReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_mgnt_78df39357633d749, []int{1}
}
func (m *ClearQuotaReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearQuotaReq.Unmarshal(m, b)
}
func (m *ClearQuotaReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearQuotaReq.Marshal(b, m, deterministic)
}
func (dst *ClearQuotaReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearQuotaReq.Merge(dst, src)
}
func (m *ClearQuotaReq) XXX_Size() int {
	return xxx_messageInfo_ClearQuotaReq.Size(m)
}
func (m *ClearQuotaReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearQuotaReq.DiscardUnknown(m)
}

var xxx_messageInfo_ClearQuotaReq proto.InternalMessageInfo

func (m *ClearQuotaReq) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *ClearQuotaReq) GetBody() *ClearQuotaReq_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type ClearQuotaReq_Body struct {
	Appid                string   `protobuf:"bytes,1,opt,name=appid" json:"appid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearQuotaReq_Body) Reset()         { *m = ClearQuotaReq_Body{} }
func (m *ClearQuotaReq_Body) String() string { return proto.CompactTextString(m) }
func (*ClearQuotaReq_Body) ProtoMessage()    {}
func (*ClearQuotaReq_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_mgnt_78df39357633d749, []int{1, 0}
}
func (m *ClearQuotaReq_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearQuotaReq_Body.Unmarshal(m, b)
}
func (m *ClearQuotaReq_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearQuotaReq_Body.Marshal(b, m, deterministic)
}
func (dst *ClearQuotaReq_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearQuotaReq_Body.Merge(dst, src)
}
func (m *ClearQuotaReq_Body) XXX_Size() int {
	return xxx_messageInfo_ClearQuotaReq_Body.Size(m)
}
func (m *ClearQuotaReq_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearQuotaReq_Body.DiscardUnknown(m)
}

var xxx_messageInfo_ClearQuotaReq_Body proto.InternalMessageInfo

func (m *ClearQuotaReq_Body) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

type ClearQuotaRes struct {
	Errcode              int32    `protobuf:"varint,1,opt,name=errcode" json:"errcode,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearQuotaRes) Reset()         { *m = ClearQuotaRes{} }
func (m *ClearQuotaRes) String() string { return proto.CompactTextString(m) }
func (*ClearQuotaRes) ProtoMessage()    {}
func (*ClearQuotaRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_mgnt_78df39357633d749, []int{2}
}
func (m *ClearQuotaRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearQuotaRes.Unmarshal(m, b)
}
func (m *ClearQuotaRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearQuotaRes.Marshal(b, m, deterministic)
}
func (dst *ClearQuotaRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearQuotaRes.Merge(dst, src)
}
func (m *ClearQuotaRes) XXX_Size() int {
	return xxx_messageInfo_ClearQuotaRes.Size(m)
}
func (m *ClearQuotaRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearQuotaRes.DiscardUnknown(m)
}

var xxx_messageInfo_ClearQuotaRes proto.InternalMessageInfo

func (m *ClearQuotaRes) GetErrcode() int32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *ClearQuotaRes) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

type GetApiQuotaReq struct {
	AccessToken          string               `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	Body                 *GetApiQuotaReq_Body `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetApiQuotaReq) Reset()         { *m = GetApiQuotaReq{} }
func (m *GetApiQuotaReq) String() string { return proto.CompactTextString(m) }
func (*GetApiQuotaReq) ProtoMessage()    {}
func (*GetApiQuotaReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_mgnt_78df39357633d749, []int{3}
}
func (m *GetApiQuotaReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApiQuotaReq.Unmarshal(m, b)
}
func (m *GetApiQuotaReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApiQuotaReq.Marshal(b, m, deterministic)
}
func (dst *GetApiQuotaReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApiQuotaReq.Merge(dst, src)
}
func (m *GetApiQuotaReq) XXX_Size() int {
	return xxx_messageInfo_GetApiQuotaReq.Size(m)
}
func (m *GetApiQuotaReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApiQuotaReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetApiQuotaReq proto.InternalMessageInfo

func (m *GetApiQuotaReq) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GetApiQuotaReq) GetBody() *GetApiQuotaReq_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type GetApiQuotaReq_Body struct {
	CgiPath              string   `protobuf:"bytes,1,opt,name=cgi_path,json=cgiPath" json:"cgi_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetApiQuotaReq_Body) Reset()         { *m = GetApiQuotaReq_Body{} }
func (m *GetApiQuotaReq_Body) String() string { return proto.CompactTextString(m) }
func (*GetApiQuotaReq_Body) ProtoMessage()    {}
func (*GetApiQuotaReq_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_mgnt_78df39357633d749, []int{3, 0}
}
func (m *GetApiQuotaReq_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApiQuotaReq_Body.Unmarshal(m, b)
}
func (m *GetApiQuotaReq_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApiQuotaReq_Body.Marshal(b, m, deterministic)
}
func (dst *GetApiQuotaReq_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApiQuotaReq_Body.Merge(dst, src)
}
func (m *GetApiQuotaReq_Body) XXX_Size() int {
	return xxx_messageInfo_GetApiQuotaReq_Body.Size(m)
}
func (m *GetApiQuotaReq_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApiQuotaReq_Body.DiscardUnknown(m)
}

var xxx_messageInfo_GetApiQuotaReq_Body proto.InternalMessageInfo

func (m *GetApiQuotaReq_Body) GetCgiPath() string {
	if m != nil {
		return m.CgiPath
	}
	return ""
}

type GetApiQuotaRes struct {
	Errcode              int32                 `protobuf:"varint,1,opt,name=errcode" json:"errcode,omitempty"`
	Errmsg               string                `protobuf:"bytes,2,opt,name=errmsg" json:"errmsg,omitempty"`
	Quota                *GetApiQuotaRes_Quota `protobuf:"bytes,3,opt,name=quota" json:"quota,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetApiQuotaRes) Reset()         { *m = GetApiQuotaRes{} }
func (m *GetApiQuotaRes) String() string { return proto.CompactTextString(m) }
func (*GetApiQuotaRes) ProtoMessage()    {}
func (*GetApiQuotaRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_mgnt_78df39357633d749, []int{4}
}
func (m *GetApiQuotaRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApiQuotaRes.Unmarshal(m, b)
}
func (m *GetApiQuotaRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApiQuotaRes.Marshal(b, m, deterministic)
}
func (dst *GetApiQuotaRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApiQuotaRes.Merge(dst, src)
}
func (m *GetApiQuotaRes) XXX_Size() int {
	return xxx_messageInfo_GetApiQuotaRes.Size(m)
}
func (m *GetApiQuotaRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApiQuotaRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetApiQuotaRes proto.InternalMessageInfo

func (m *GetApiQuotaRes) GetErrcode() int32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *GetApiQuotaRes) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *GetApiQuotaRes) GetQuota() *GetApiQuotaRes_Quota {
	if m != nil {
		return m.Quota
	}
	return nil
}

type GetApiQuotaRes_Quota struct {
	DailyLimit           int32    `protobuf:"varint,1,opt,name=daily_limit,json=dailyLimit" json:"daily_limit,omitempty"`
	Used                 int32    `protobuf:"varint,2,opt,name=used" json:"used,omitempty"`
	Remain               int32    `protobuf:"varint,3,opt,name=remain" json:"remain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetApiQuotaRes_Quota) Reset()         { *m = GetApiQuotaRes_Quota{} }
func (m *GetApiQuotaRes_Quota) String() string { return proto.CompactTextString(m) }
func (*GetApiQuotaRes_Quota) ProtoMessage()    {}
func (*GetApiQuotaRes_Quota) Descriptor() ([]byte, []int) {
	return fileDescriptor_mgnt_78df39357633d749, []int{4, 0}
}
func (m *GetApiQuotaRes_Quota) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApiQuotaRes_Quota.Unmarshal(m, b)
}
func (m *GetApiQuotaRes_Quota) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApiQuotaRes_Quota.Marshal(b, m, deterministic)
}
func (dst *GetApiQuotaRes_Quota) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApiQuotaRes_Quota.Merge(dst, src)
}
func (m *GetApiQuotaRes_Quota) XXX_Size() int {
	return xxx_messageInfo_GetApiQuotaRes_Quota.Size(m)
}
func (m *GetApiQuotaRes_Quota) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApiQuotaRes_Quota.DiscardUnknown(m)
}

var xxx_messageInfo_GetApiQuotaRes_Quota proto.InternalMessageInfo

func (m *GetApiQuotaRes_Quota) GetDailyLimit() int32 {
	if m != nil {
		return m.DailyLimit
	}
	return 0
}

func (m *GetApiQuotaRes_Quota) GetUsed() int32 {
	if m != nil {
		return m.Used
	}
	return 0
}

func (m *GetApiQuotaRes_Quota) GetRemain() int32 {
	if m != nil {
		return m.Remain
	}
	return 0
}

type GetRidInfoReq struct {
	AccessToken          string              `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	Body                 *GetRidInfoReq_Body `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetRidInfoReq) Reset()         { *m = GetRidInfoReq{} }
func (m *GetRidInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetRidInfoReq) ProtoMessage()    {}
func (*GetRidInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_mgnt_78df39357633d749, []int{5}
}
func (m *GetRidInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRidInfoReq.Unmarshal(m, b)
}
func (m *GetRidInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRidInfoReq.Marshal(b, m, deterministic)
}
func (dst *GetRidInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRidInfoReq.Merge(dst, src)
}
func (m *GetRidInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetRidInfoReq.Size(m)
}
func (m *GetRidInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRidInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetRidInfoReq proto.InternalMessageInfo

func (m *GetRidInfoReq) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GetRidInfoReq) GetBody() *GetRidInfoReq_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type GetRidInfoReq_Body struct {
	Rid                  string   `protobuf:"bytes,1,opt,name=rid" json:"rid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRidInfoReq_Body) Reset()         { *m = GetRidInfoReq_Body{} }
func (m *GetRidInfoReq_Body) String() string { return proto.CompactTextString(m) }
func (*GetRidInfoReq_Body) ProtoMessage()    {}
func (*GetRidInfoReq_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_mgnt_78df39357633d749, []int{5, 0}
}
func (m *GetRidInfoReq_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRidInfoReq_Body.Unmarshal(m, b)
}
func (m *GetRidInfoReq_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRidInfoReq_Body.Marshal(b, m, deterministic)
}
func (dst *GetRidInfoReq_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRidInfoReq_Body.Merge(dst, src)
}
func (m *GetRidInfoReq_Body) XXX_Size() int {
	return xxx_messageInfo_GetRidInfoReq_Body.Size(m)
}
func (m *GetRidInfoReq_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRidInfoReq_Body.DiscardUnknown(m)
}

var xxx_messageInfo_GetRidInfoReq_Body proto.InternalMessageInfo

func (m *GetRidInfoReq_Body) GetRid() string {
	if m != nil {
		return m.Rid
	}
	return ""
}

type GetRidInfoRes struct {
	Errcode              int32                  `protobuf:"varint,1,opt,name=errcode" json:"errcode,omitempty"`
	Errmsg               string                 `protobuf:"bytes,2,opt,name=errmsg" json:"errmsg,omitempty"`
	Request              *GetRidInfoRes_Request `protobuf:"bytes,3,opt,name=request" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetRidInfoRes) Reset()         { *m = GetRidInfoRes{} }
func (m *GetRidInfoRes) String() string { return proto.CompactTextString(m) }
func (*GetRidInfoRes) ProtoMessage()    {}
func (*GetRidInfoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_mgnt_78df39357633d749, []int{6}
}
func (m *GetRidInfoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRidInfoRes.Unmarshal(m, b)
}
func (m *GetRidInfoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRidInfoRes.Marshal(b, m, deterministic)
}
func (dst *GetRidInfoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRidInfoRes.Merge(dst, src)
}
func (m *GetRidInfoRes) XXX_Size() int {
	return xxx_messageInfo_GetRidInfoRes.Size(m)
}
func (m *GetRidInfoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRidInfoRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetRidInfoRes proto.InternalMessageInfo

func (m *GetRidInfoRes) GetErrcode() int32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *GetRidInfoRes) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *GetRidInfoRes) GetRequest() *GetRidInfoRes_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

type GetRidInfoRes_Request struct {
	InvokeTime           int64    `protobuf:"varint,1,opt,name=invoke_time,json=invokeTime" json:"invoke_time,omitempty"`
	CostInMs             int64    `protobuf:"varint,2,opt,name=cost_in_ms,json=costInMs" json:"cost_in_ms,omitempty"`
	RequestUrl           string   `protobuf:"bytes,3,opt,name=request_url,json=requestUrl" json:"request_url,omitempty"`
	RequestBody          string   `protobuf:"bytes,4,opt,name=request_body,json=requestBody" json:"request_body,omitempty"`
	ResponseBody         string   `protobuf:"bytes,5,opt,name=response_body,json=responseBody" json:"response_body,omitempty"`
	ClientIp             string   `protobuf:"bytes,6,opt,name=client_ip,json=clientIp" json:"client_ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRidInfoRes_Request) Reset()         { *m = GetRidInfoRes_Request{} }
func (m *GetRidInfoRes_Request) String() string { return proto.CompactTextString(m) }
func (*GetRidInfoRes_Request) ProtoMessage()    {}
func (*GetRidInfoRes_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_mgnt_78df39357633d749, []int{6, 0}
}
func (m *GetRidInfoRes_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRidInfoRes_Request.Unmarshal(m, b)
}
func (m *GetRidInfoRes_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRidInfoRes_Request.Marshal(b, m, deterministic)
}
func (dst *GetRidInfoRes_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRidInfoRes_Request.Merge(dst, src)
}
func (m *GetRidInfoRes_Request) XXX_Size() int {
	return xxx_messageInfo_GetRidInfoRes_Request.Size(m)
}
func (m *GetRidInfoRes_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRidInfoRes_Request.DiscardUnknown(m)
}

var xxx_messageInfo_GetRidInfoRes_Request proto.InternalMessageInfo

func (m *GetRidInfoRes_Request) GetInvokeTime() int64 {
	if m != nil {
		return m.InvokeTime
	}
	return 0
}

func (m *GetRidInfoRes_Request) GetCostInMs() int64 {
	if m != nil {
		return m.CostInMs
	}
	return 0
}

func (m *GetRidInfoRes_Request) GetRequestUrl() string {
	if m != nil {
		return m.RequestUrl
	}
	return ""
}

func (m *GetRidInfoRes_Request) GetRequestBody() string {
	if m != nil {
		return m.RequestBody
	}
	return ""
}

func (m *GetRidInfoRes_Request) GetResponseBody() string {
	if m != nil {
		return m.ResponseBody
	}
	return ""
}

func (m *GetRidInfoRes_Request) GetClientIp() string {
	if m != nil {
		return m.ClientIp
	}
	return ""
}

type ClearQuotaV2Req struct {
	Appid                string   `protobuf:"bytes,1,opt,name=appid" json:"appid,omitempty"`
	Appsecret            string   `protobuf:"bytes,2,opt,name=appsecret" json:"appsecret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearQuotaV2Req) Reset()         { *m = ClearQuotaV2Req{} }
func (m *ClearQuotaV2Req) String() string { return proto.CompactTextString(m) }
func (*ClearQuotaV2Req) ProtoMessage()    {}
func (*ClearQuotaV2Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_mgnt_78df39357633d749, []int{7}
}
func (m *ClearQuotaV2Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearQuotaV2Req.Unmarshal(m, b)
}
func (m *ClearQuotaV2Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearQuotaV2Req.Marshal(b, m, deterministic)
}
func (dst *ClearQuotaV2Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearQuotaV2Req.Merge(dst, src)
}
func (m *ClearQuotaV2Req) XXX_Size() int {
	return xxx_messageInfo_ClearQuotaV2Req.Size(m)
}
func (m *ClearQuotaV2Req) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearQuotaV2Req.DiscardUnknown(m)
}

var xxx_messageInfo_ClearQuotaV2Req proto.InternalMessageInfo

func (m *ClearQuotaV2Req) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *ClearQuotaV2Req) GetAppsecret() string {
	if m != nil {
		return m.Appsecret
	}
	return ""
}

type ClearQuotaV2Res struct {
	Errcode              int32    `protobuf:"varint,1,opt,name=errcode" json:"errcode,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearQuotaV2Res) Reset()         { *m = ClearQuotaV2Res{} }
func (m *ClearQuotaV2Res) String() string { return proto.CompactTextString(m) }
func (*ClearQuotaV2Res) ProtoMessage()    {}
func (*ClearQuotaV2Res) Descriptor() ([]byte, []int) {
	return fileDescriptor_mgnt_78df39357633d749, []int{8}
}
func (m *ClearQuotaV2Res) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearQuotaV2Res.Unmarshal(m, b)
}
func (m *ClearQuotaV2Res) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearQuotaV2Res.Marshal(b, m, deterministic)
}
func (dst *ClearQuotaV2Res) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearQuotaV2Res.Merge(dst, src)
}
func (m *ClearQuotaV2Res) XXX_Size() int {
	return xxx_messageInfo_ClearQuotaV2Res.Size(m)
}
func (m *ClearQuotaV2Res) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearQuotaV2Res.DiscardUnknown(m)
}

var xxx_messageInfo_ClearQuotaV2Res proto.InternalMessageInfo

func (m *ClearQuotaV2Res) GetErrcode() int32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *ClearQuotaV2Res) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func init() {
	proto.RegisterType((*ClearQuotaData)(nil), "api.weixin.qq.com.ClearQuotaData")
	proto.RegisterType((*ClearQuotaReq)(nil), "api.weixin.qq.com.ClearQuotaReq")
	proto.RegisterType((*ClearQuotaReq_Body)(nil), "api.weixin.qq.com.ClearQuotaReq.Body")
	proto.RegisterType((*ClearQuotaRes)(nil), "api.weixin.qq.com.ClearQuotaRes")
	proto.RegisterType((*GetApiQuotaReq)(nil), "api.weixin.qq.com.GetApiQuotaReq")
	proto.RegisterType((*GetApiQuotaReq_Body)(nil), "api.weixin.qq.com.GetApiQuotaReq.Body")
	proto.RegisterType((*GetApiQuotaRes)(nil), "api.weixin.qq.com.GetApiQuotaRes")
	proto.RegisterType((*GetApiQuotaRes_Quota)(nil), "api.weixin.qq.com.GetApiQuotaRes.Quota")
	proto.RegisterType((*GetRidInfoReq)(nil), "api.weixin.qq.com.GetRidInfoReq")
	proto.RegisterType((*GetRidInfoReq_Body)(nil), "api.weixin.qq.com.GetRidInfoReq.Body")
	proto.RegisterType((*GetRidInfoRes)(nil), "api.weixin.qq.com.GetRidInfoRes")
	proto.RegisterType((*GetRidInfoRes_Request)(nil), "api.weixin.qq.com.GetRidInfoRes.Request")
	proto.RegisterType((*ClearQuotaV2Req)(nil), "api.weixin.qq.com.ClearQuotaV2Req")
	proto.RegisterType((*ClearQuotaV2Res)(nil), "api.weixin.qq.com.ClearQuotaV2Res")
}

func init() { proto.RegisterFile("wx-miniprogram/mgnt.proto", fileDescriptor_mgnt_78df39357633d749) }

var fileDescriptor_mgnt_78df39357633d749 = []byte{
	// 753 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcf, 0x6f, 0xe3, 0x44,
	0x14, 0x96, 0x9b, 0xa4, 0x69, 0x5e, 0xda, 0x02, 0x23, 0x04, 0xa9, 0x89, 0x44, 0x3b, 0xa8, 0x3f,
	0x84, 0x54, 0x1b, 0x05, 0x84, 0xa0, 0xa2, 0x45, 0x4d, 0x8b, 0xaa, 0x4a, 0x54, 0x02, 0x53, 0x38,
	0x70, 0xb1, 0x26, 0xf6, 0xe0, 0x8e, 0x1a, 0xcf, 0x38, 0x33, 0x93, 0xb4, 0x05, 0x71, 0xe1, 0xc2,
	0x81, 0x0b, 0xda, 0xdd, 0xcb, 0xfe, 0x53, 0xbb, 0x87, 0x95, 0x76, 0xff, 0x81, 0xfd, 0x43, 0x56,
	0x1e, 0x3b, 0x4d, 0xdc, 0x66, 0xd7, 0xdd, 0x6a, 0x6f, 0xf3, 0x3e, 0x7f, 0xef, 0xcd, 0xf7, 0xbe,
	0x79, 0x33, 0x86, 0x95, 0x8b, 0xcb, 0xed, 0x98, 0x71, 0x96, 0x48, 0x11, 0x49, 0x12, 0xbb, 0x71,
	0xc4, 0xb5, 0x93, 0x48, 0xa1, 0x05, 0xfa, 0x80, 0x24, 0xcc, 0xb9, 0xa0, 0xec, 0x92, 0x71, 0x67,
	0x30, 0x70, 0x02, 0x11, 0xdb, 0xed, 0x48, 0x88, 0xa8, 0x4f, 0x5d, 0x92, 0x30, 0x97, 0x70, 0x2e,
	0x34, 0xd1, 0x4c, 0x70, 0x95, 0x25, 0xe0, 0x0d, 0x58, 0x3e, 0xe8, 0x53, 0x22, 0x7f, 0x1e, 0x0a,
	0x4d, 0x0e, 0x89, 0x26, 0xe8, 0x43, 0xa8, 0x91, 0x24, 0x61, 0x61, 0xcb, 0x5a, 0xb5, 0xb6, 0x1a,
	0x5e, 0x16, 0xe0, 0xff, 0x2c, 0x58, 0x9a, 0x10, 0x3d, 0x3a, 0x40, 0x6b, 0xb0, 0x48, 0x82, 0x80,
	0x2a, 0xe5, 0x6b, 0x71, 0x4e, 0x79, 0x4e, 0x6f, 0x66, 0xd8, 0x69, 0x0a, 0xa1, 0x6f, 0xa1, 0xda,
	0x13, 0xe1, 0x55, 0x6b, 0x6e, 0xd5, 0xda, 0x6a, 0x76, 0xd6, 0x9d, 0x5b, 0xe2, 0x9c, 0x42, 0x49,
	0xa7, 0x2b, 0xc2, 0x2b, 0xcf, 0xa4, 0xd8, 0x6d, 0xa8, 0xa6, 0xd1, 0x6b, 0xd4, 0xec, 0x17, 0xc5,
	0x28, 0xd4, 0x82, 0x3a, 0x95, 0x32, 0x10, 0x21, 0x35, 0xc4, 0x9a, 0x37, 0x0e, 0xd1, 0x47, 0x30,
	0x4f, 0xa5, 0x8c, 0x55, 0x64, 0x54, 0x34, 0xbc, 0x3c, 0xc2, 0x0f, 0x2c, 0x58, 0x3e, 0xa2, 0x7a,
	0x3f, 0x61, 0x6f, 0xd3, 0xd1, 0x4e, 0xa1, 0xa3, 0x8d, 0x19, 0x1d, 0x15, 0x6b, 0x4e, 0xb7, 0xb4,
	0x96, 0xb7, 0xb4, 0x02, 0x0b, 0x41, 0xc4, 0xfc, 0x84, 0xe8, 0xb3, 0x7c, 0x8b, 0x7a, 0x10, 0xb1,
	0x9f, 0x88, 0x3e, 0xc3, 0x2f, 0x6e, 0x8a, 0xba, 0x47, 0x67, 0x68, 0x17, 0x6a, 0x83, 0x34, 0xbb,
	0x55, 0x31, 0x22, 0x37, 0xcb, 0x44, 0x2a, 0x27, 0x5b, 0x64, 0x59, 0xf6, 0x29, 0xd4, 0x4c, 0x8c,
	0x3e, 0x85, 0x66, 0x48, 0x58, 0xff, 0xca, 0xef, 0xb3, 0x98, 0xe9, 0x7c, 0x77, 0x30, 0xd0, 0x8f,
	0x29, 0x82, 0x10, 0x54, 0x87, 0x8a, 0x86, 0x66, 0xfb, 0x9a, 0x67, 0xd6, 0xa9, 0x28, 0x49, 0x63,
	0xc2, 0xb8, 0xd9, 0xbd, 0xe6, 0xe5, 0x11, 0xfe, 0xd7, 0x82, 0xa5, 0x23, 0xaa, 0x3d, 0x16, 0x1e,
	0xf3, 0x3f, 0xc4, 0x3b, 0x9b, 0x9f, 0x42, 0xc9, 0x69, 0xb3, 0x5b, 0xb9, 0xd9, 0xef, 0x43, 0x45,
	0x5e, 0x4f, 0x4f, 0xba, 0xc4, 0xcf, 0xe7, 0x8a, 0x4a, 0xee, 0x63, 0x71, 0x17, 0xea, 0x92, 0x0e,
	0x86, 0x54, 0xe9, 0xdc, 0xe4, 0xad, 0x12, 0x6d, 0xca, 0xf1, 0x32, 0xbe, 0x37, 0x4e, 0xb4, 0x9f,
	0x58, 0x50, 0xcf, 0xc1, 0xd4, 0x6a, 0xc6, 0x47, 0xe2, 0x9c, 0xfa, 0x9a, 0xc5, 0x99, 0x8a, 0x8a,
	0x07, 0x19, 0x74, 0xca, 0x62, 0x8a, 0xda, 0x00, 0x81, 0x50, 0xda, 0x67, 0xdc, 0x8f, 0x95, 0x11,
	0x53, 0xf1, 0x16, 0x52, 0xe4, 0x98, 0x9f, 0xa8, 0x34, 0x3d, 0xaf, 0xea, 0x0f, 0x65, 0xdf, 0x48,
	0x6a, 0x78, 0x90, 0x43, 0xbf, 0xca, 0x7e, 0xea, 0xf5, 0x98, 0x60, 0x0c, 0xad, 0x66, 0x5e, 0xe7,
	0x98, 0x31, 0xea, 0x33, 0x58, 0x92, 0x54, 0x25, 0x82, 0x2b, 0x9a, 0x71, 0x6a, 0x86, 0xb3, 0x38,
	0x06, 0x0d, 0xe9, 0x13, 0x68, 0x04, 0x7d, 0x46, 0xb9, 0xf6, 0x59, 0xd2, 0x9a, 0x37, 0x84, 0x85,
	0x0c, 0x38, 0x4e, 0xf0, 0x0f, 0xf0, 0xde, 0xe4, 0x52, 0xfe, 0xd6, 0x49, 0xcf, 0x78, 0xe6, 0xed,
	0x45, 0x6d, 0x68, 0x90, 0x24, 0x51, 0x34, 0x90, 0x54, 0xe7, 0xc6, 0x4e, 0x00, 0x7c, 0x70, 0xb3,
	0xcc, 0x3d, 0x0e, 0xa8, 0xf3, 0xb4, 0x0a, 0xcd, 0x93, 0x88, 0xeb, 0x5f, 0xa8, 0x1c, 0xb1, 0x80,
	0xa2, 0xff, 0x2d, 0x80, 0x49, 0x55, 0xb4, 0x5a, 0xf6, 0x14, 0xd9, 0x65, 0x0c, 0x85, 0xf7, 0xfe,
	0x79, 0xf6, 0xf2, 0xe1, 0xdc, 0x37, 0xf8, 0x0b, 0x37, 0x88, 0xd8, 0x76, 0x8f, 0x71, 0x37, 0x48,
	0xbf, 0xfb, 0xe6, 0x16, 0x7d, 0x3f, 0x3d, 0xda, 0xbb, 0x7f, 0x4d, 0x47, 0x7f, 0xef, 0x98, 0x09,
	0x45, 0x8f, 0x2d, 0x68, 0x4e, 0xdd, 0x43, 0xb4, 0x56, 0xfa, 0x98, 0xd8, 0xa5, 0x14, 0x85, 0x0f,
	0x8d, 0xaa, 0x3d, 0xfc, 0xf5, 0xb5, 0x2a, 0x91, 0x50, 0x9e, 0xbe, 0xfd, 0x46, 0x97, 0x1b, 0x51,
	0x7d, 0x07, 0x6d, 0x8f, 0x2c, 0x80, 0xc9, 0xf8, 0xce, 0xb4, 0xab, 0x70, 0xf3, 0xec, 0x32, 0x86,
	0xc2, 0x5d, 0x23, 0xec, 0x3b, 0xfc, 0xd5, 0x2d, 0x61, 0x92, 0x85, 0x77, 0x94, 0xf5, 0x27, 0x2c,
	0x4e, 0x8f, 0x06, 0xc2, 0x6f, 0x3c, 0x24, 0x33, 0x82, 0x76, 0x39, 0x47, 0x61, 0x6c, 0xb4, 0xb5,
	0xf1, 0xc7, 0xb3, 0x8e, 0xd2, 0x1d, 0x75, 0x76, 0xac, 0xcf, 0xbb, 0x9b, 0xbf, 0xaf, 0x47, 0x4c,
	0x9f, 0x0d, 0x7b, 0x69, 0x05, 0x37, 0xa4, 0xa3, 0xed, 0xb1, 0xfe, 0xe2, 0xdf, 0xb8, 0x37, 0x6f,
	0x7e, 0xac, 0x5f, 0xbe, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x77, 0xe3, 0x86, 0xb1, 0xa6, 0x07, 0x00,
	0x00,
}
