// 微信小程序接口-openapi管理 weixin-miniprogram

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.0
// source: wx-miniprogram/mgnt.proto

package wx_miniprogram

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClearQuotaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Appid string `protobuf:"bytes,1,opt,name=appid,proto3" json:"appid,omitempty"` // 要被清空的账号的appid
}

func (x *ClearQuotaData) Reset() {
	*x = ClearQuotaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_miniprogram_mgnt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearQuotaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearQuotaData) ProtoMessage() {}

func (x *ClearQuotaData) ProtoReflect() protoreflect.Message {
	mi := &file_wx_miniprogram_mgnt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearQuotaData.ProtoReflect.Descriptor instead.
func (*ClearQuotaData) Descriptor() ([]byte, []int) {
	return file_wx_miniprogram_mgnt_proto_rawDescGZIP(), []int{0}
}

func (x *ClearQuotaData) GetAppid() string {
	if x != nil {
		return x.Appid
	}
	return ""
}

type ClearQuotaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string              `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"` // 接口调用凭证，该参数为 URL 参数，非 Body 参数。使用access_token或者authorizer_access_token
	Body        *ClearQuotaReq_Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`                                  // 要被清空的账号的appid
}

func (x *ClearQuotaReq) Reset() {
	*x = ClearQuotaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_miniprogram_mgnt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearQuotaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearQuotaReq) ProtoMessage() {}

func (x *ClearQuotaReq) ProtoReflect() protoreflect.Message {
	mi := &file_wx_miniprogram_mgnt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearQuotaReq.ProtoReflect.Descriptor instead.
func (*ClearQuotaReq) Descriptor() ([]byte, []int) {
	return file_wx_miniprogram_mgnt_proto_rawDescGZIP(), []int{1}
}

func (x *ClearQuotaReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ClearQuotaReq) GetBody() *ClearQuotaReq_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

type ClearQuotaRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errcode int32  `protobuf:"varint,1,opt,name=errcode,proto3" json:"errcode,omitempty"` // 错误码
	Errmsg  string `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`    // 错误信息
}

func (x *ClearQuotaRes) Reset() {
	*x = ClearQuotaRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_miniprogram_mgnt_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearQuotaRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearQuotaRes) ProtoMessage() {}

func (x *ClearQuotaRes) ProtoReflect() protoreflect.Message {
	mi := &file_wx_miniprogram_mgnt_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearQuotaRes.ProtoReflect.Descriptor instead.
func (*ClearQuotaRes) Descriptor() ([]byte, []int) {
	return file_wx_miniprogram_mgnt_proto_rawDescGZIP(), []int{2}
}

func (x *ClearQuotaRes) GetErrcode() int32 {
	if x != nil {
		return x.Errcode
	}
	return 0
}

func (x *ClearQuotaRes) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

type GetApiQuotaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string               `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"` // 接口调用凭证，该参数为 URL 参数，非 Body 参数。使用access_token或者authorizer_access_token
	Body        *GetApiQuotaReq_Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`                                  // api的请求地址，例如"/cgi-bin/message/custom/send";不要前缀“https://api.weixin.qq.com” ，也不要漏了"/",否则都会76003的报错
}

func (x *GetApiQuotaReq) Reset() {
	*x = GetApiQuotaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_miniprogram_mgnt_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetApiQuotaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiQuotaReq) ProtoMessage() {}

func (x *GetApiQuotaReq) ProtoReflect() protoreflect.Message {
	mi := &file_wx_miniprogram_mgnt_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiQuotaReq.ProtoReflect.Descriptor instead.
func (*GetApiQuotaReq) Descriptor() ([]byte, []int) {
	return file_wx_miniprogram_mgnt_proto_rawDescGZIP(), []int{3}
}

func (x *GetApiQuotaReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GetApiQuotaReq) GetBody() *GetApiQuotaReq_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

type GetApiQuotaRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errcode int32                 `protobuf:"varint,1,opt,name=errcode,proto3" json:"errcode,omitempty"` // 返回码
	Errmsg  string                `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`    // 错误信息
	Quota   *GetApiQuotaRes_Quota `protobuf:"bytes,3,opt,name=quota,proto3" json:"quota,omitempty"`      // quota详情
}

func (x *GetApiQuotaRes) Reset() {
	*x = GetApiQuotaRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_miniprogram_mgnt_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetApiQuotaRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiQuotaRes) ProtoMessage() {}

func (x *GetApiQuotaRes) ProtoReflect() protoreflect.Message {
	mi := &file_wx_miniprogram_mgnt_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiQuotaRes.ProtoReflect.Descriptor instead.
func (*GetApiQuotaRes) Descriptor() ([]byte, []int) {
	return file_wx_miniprogram_mgnt_proto_rawDescGZIP(), []int{4}
}

func (x *GetApiQuotaRes) GetErrcode() int32 {
	if x != nil {
		return x.Errcode
	}
	return 0
}

func (x *GetApiQuotaRes) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

func (x *GetApiQuotaRes) GetQuota() *GetApiQuotaRes_Quota {
	if x != nil {
		return x.Quota
	}
	return nil
}

type GetRidInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string              `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Body        *GetRidInfoReq_Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *GetRidInfoReq) Reset() {
	*x = GetRidInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_miniprogram_mgnt_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRidInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRidInfoReq) ProtoMessage() {}

func (x *GetRidInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_wx_miniprogram_mgnt_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRidInfoReq.ProtoReflect.Descriptor instead.
func (*GetRidInfoReq) Descriptor() ([]byte, []int) {
	return file_wx_miniprogram_mgnt_proto_rawDescGZIP(), []int{5}
}

func (x *GetRidInfoReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GetRidInfoReq) GetBody() *GetRidInfoReq_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

type GetRidInfoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errcode int32                  `protobuf:"varint,1,opt,name=errcode,proto3" json:"errcode,omitempty"`
	Errmsg  string                 `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Request *GetRidInfoRes_Request `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"` // 该 rid 对应的请求详情
}

func (x *GetRidInfoRes) Reset() {
	*x = GetRidInfoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_miniprogram_mgnt_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRidInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRidInfoRes) ProtoMessage() {}

func (x *GetRidInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_wx_miniprogram_mgnt_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRidInfoRes.ProtoReflect.Descriptor instead.
func (*GetRidInfoRes) Descriptor() ([]byte, []int) {
	return file_wx_miniprogram_mgnt_proto_rawDescGZIP(), []int{6}
}

func (x *GetRidInfoRes) GetErrcode() int32 {
	if x != nil {
		return x.Errcode
	}
	return 0
}

func (x *GetRidInfoRes) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

func (x *GetRidInfoRes) GetRequest() *GetRidInfoRes_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

type ClearQuotaV2Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Appid     string `protobuf:"bytes,1,opt,name=appid,proto3" json:"appid,omitempty"`         // 要被清空的账号的appid
	Appsecret string `protobuf:"bytes,2,opt,name=appsecret,proto3" json:"appsecret,omitempty"` // 唯一凭证密钥，即 AppSecret，获取方式同 appid
}

func (x *ClearQuotaV2Req) Reset() {
	*x = ClearQuotaV2Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_miniprogram_mgnt_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearQuotaV2Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearQuotaV2Req) ProtoMessage() {}

func (x *ClearQuotaV2Req) ProtoReflect() protoreflect.Message {
	mi := &file_wx_miniprogram_mgnt_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearQuotaV2Req.ProtoReflect.Descriptor instead.
func (*ClearQuotaV2Req) Descriptor() ([]byte, []int) {
	return file_wx_miniprogram_mgnt_proto_rawDescGZIP(), []int{7}
}

func (x *ClearQuotaV2Req) GetAppid() string {
	if x != nil {
		return x.Appid
	}
	return ""
}

func (x *ClearQuotaV2Req) GetAppsecret() string {
	if x != nil {
		return x.Appsecret
	}
	return ""
}

type ClearQuotaV2Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errcode int32  `protobuf:"varint,1,opt,name=errcode,proto3" json:"errcode,omitempty"` // 错误码
	Errmsg  string `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`    // 错误信息
}

func (x *ClearQuotaV2Res) Reset() {
	*x = ClearQuotaV2Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_miniprogram_mgnt_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearQuotaV2Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearQuotaV2Res) ProtoMessage() {}

func (x *ClearQuotaV2Res) ProtoReflect() protoreflect.Message {
	mi := &file_wx_miniprogram_mgnt_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearQuotaV2Res.ProtoReflect.Descriptor instead.
func (*ClearQuotaV2Res) Descriptor() ([]byte, []int) {
	return file_wx_miniprogram_mgnt_proto_rawDescGZIP(), []int{8}
}

func (x *ClearQuotaV2Res) GetErrcode() int32 {
	if x != nil {
		return x.Errcode
	}
	return 0
}

func (x *ClearQuotaV2Res) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

type ClearQuotaReq_Body struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Appid string `protobuf:"bytes,1,opt,name=appid,proto3" json:"appid,omitempty"`
}

func (x *ClearQuotaReq_Body) Reset() {
	*x = ClearQuotaReq_Body{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_miniprogram_mgnt_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearQuotaReq_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearQuotaReq_Body) ProtoMessage() {}

func (x *ClearQuotaReq_Body) ProtoReflect() protoreflect.Message {
	mi := &file_wx_miniprogram_mgnt_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearQuotaReq_Body.ProtoReflect.Descriptor instead.
func (*ClearQuotaReq_Body) Descriptor() ([]byte, []int) {
	return file_wx_miniprogram_mgnt_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ClearQuotaReq_Body) GetAppid() string {
	if x != nil {
		return x.Appid
	}
	return ""
}

type GetApiQuotaReq_Body struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CgiPath string `protobuf:"bytes,1,opt,name=cgi_path,json=cgiPath,proto3" json:"cgi_path,omitempty"`
}

func (x *GetApiQuotaReq_Body) Reset() {
	*x = GetApiQuotaReq_Body{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_miniprogram_mgnt_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetApiQuotaReq_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiQuotaReq_Body) ProtoMessage() {}

func (x *GetApiQuotaReq_Body) ProtoReflect() protoreflect.Message {
	mi := &file_wx_miniprogram_mgnt_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiQuotaReq_Body.ProtoReflect.Descriptor instead.
func (*GetApiQuotaReq_Body) Descriptor() ([]byte, []int) {
	return file_wx_miniprogram_mgnt_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetApiQuotaReq_Body) GetCgiPath() string {
	if x != nil {
		return x.CgiPath
	}
	return ""
}

type GetApiQuotaRes_Quota struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DailyLimit int32 `protobuf:"varint,1,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"` // 当天该账号可调用该接口的次数
	Used       int32 `protobuf:"varint,2,opt,name=used,proto3" json:"used,omitempty"`                               // 当天已经调用的次数
	Remain     int32 `protobuf:"varint,3,opt,name=remain,proto3" json:"remain,omitempty"`                           // 当天剩余调用次数
}

func (x *GetApiQuotaRes_Quota) Reset() {
	*x = GetApiQuotaRes_Quota{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_miniprogram_mgnt_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetApiQuotaRes_Quota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiQuotaRes_Quota) ProtoMessage() {}

func (x *GetApiQuotaRes_Quota) ProtoReflect() protoreflect.Message {
	mi := &file_wx_miniprogram_mgnt_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiQuotaRes_Quota.ProtoReflect.Descriptor instead.
func (*GetApiQuotaRes_Quota) Descriptor() ([]byte, []int) {
	return file_wx_miniprogram_mgnt_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GetApiQuotaRes_Quota) GetDailyLimit() int32 {
	if x != nil {
		return x.DailyLimit
	}
	return 0
}

func (x *GetApiQuotaRes_Quota) GetUsed() int32 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *GetApiQuotaRes_Quota) GetRemain() int32 {
	if x != nil {
		return x.Remain
	}
	return 0
}

type GetRidInfoReq_Body struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rid string `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
}

func (x *GetRidInfoReq_Body) Reset() {
	*x = GetRidInfoReq_Body{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_miniprogram_mgnt_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRidInfoReq_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRidInfoReq_Body) ProtoMessage() {}

func (x *GetRidInfoReq_Body) ProtoReflect() protoreflect.Message {
	mi := &file_wx_miniprogram_mgnt_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRidInfoReq_Body.ProtoReflect.Descriptor instead.
func (*GetRidInfoReq_Body) Descriptor() ([]byte, []int) {
	return file_wx_miniprogram_mgnt_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GetRidInfoReq_Body) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

type GetRidInfoRes_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InvokeTime   int64  `protobuf:"varint,1,opt,name=invoke_time,json=invokeTime,proto3" json:"invoke_time,omitempty"`      // 发起请求的时间戳
	CostInMs     int64  `protobuf:"varint,2,opt,name=cost_in_ms,json=costInMs,proto3" json:"cost_in_ms,omitempty"`          // 请求毫秒级耗时
	RequestUrl   string `protobuf:"bytes,3,opt,name=request_url,json=requestUrl,proto3" json:"request_url,omitempty"`       // 请求的 URL 参数
	RequestBody  string `protobuf:"bytes,4,opt,name=request_body,json=requestBody,proto3" json:"request_body,omitempty"`    // post请求的请求参数
	ResponseBody string `protobuf:"bytes,5,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"` // 接口请求返回参数
	ClientIp     string `protobuf:"bytes,6,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`             // 接口请求的客户端ip
}

func (x *GetRidInfoRes_Request) Reset() {
	*x = GetRidInfoRes_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_miniprogram_mgnt_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRidInfoRes_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRidInfoRes_Request) ProtoMessage() {}

func (x *GetRidInfoRes_Request) ProtoReflect() protoreflect.Message {
	mi := &file_wx_miniprogram_mgnt_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRidInfoRes_Request.ProtoReflect.Descriptor instead.
func (*GetRidInfoRes_Request) Descriptor() ([]byte, []int) {
	return file_wx_miniprogram_mgnt_proto_rawDescGZIP(), []int{6, 0}
}

func (x *GetRidInfoRes_Request) GetInvokeTime() int64 {
	if x != nil {
		return x.InvokeTime
	}
	return 0
}

func (x *GetRidInfoRes_Request) GetCostInMs() int64 {
	if x != nil {
		return x.CostInMs
	}
	return 0
}

func (x *GetRidInfoRes_Request) GetRequestUrl() string {
	if x != nil {
		return x.RequestUrl
	}
	return ""
}

func (x *GetRidInfoRes_Request) GetRequestBody() string {
	if x != nil {
		return x.RequestBody
	}
	return ""
}

func (x *GetRidInfoRes_Request) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

func (x *GetRidInfoRes_Request) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

var File_wx_miniprogram_mgnt_proto protoreflect.FileDescriptor

var file_wx_miniprogram_mgnt_proto_rawDesc = []byte{
	0x0a, 0x19, 0x77, 0x78, 0x2d, 0x6d, 0x69, 0x6e, 0x69, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d,
	0x2f, 0x6d, 0x67, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x61, 0x70, 0x69,
	0x2e, 0x77, 0x65, 0x69, 0x78, 0x69, 0x6e, 0x2e, 0x71, 0x71, 0x2e, 0x63, 0x6f, 0x6d, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x0e,
	0x43, 0x6c, 0x65, 0x61, 0x72, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14,
	0x0a, 0x05, 0x61, 0x70, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61,
	0x70, 0x70, 0x69, 0x64, 0x22, 0x8b, 0x01, 0x0a, 0x0d, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x51, 0x75,
	0x6f, 0x74, 0x61, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x39, 0x0a, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65,
	0x69, 0x78, 0x69, 0x6e, 0x2e, 0x71, 0x71, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x43, 0x6c, 0x65, 0x61,
	0x72, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x71, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x1a, 0x1c, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x61, 0x70, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70,
	0x69, 0x64, 0x22, 0x41, 0x0a, 0x0d, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x51, 0x75, 0x6f, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65,
	0x72, 0x72, 0x6d, 0x73, 0x67, 0x22, 0x92, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x69,
	0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x3a, 0x0a, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x77, 0x65, 0x69, 0x78, 0x69, 0x6e, 0x2e, 0x71, 0x71, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x70, 0x69, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x71, 0x2e, 0x42, 0x6f, 0x64,
	0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x1a, 0x21, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x12,
	0x19, 0x0a, 0x08, 0x63, 0x67, 0x69, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x67, 0x69, 0x50, 0x61, 0x74, 0x68, 0x22, 0xd7, 0x01, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x41, 0x70, 0x69, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x65, 0x72, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x65, 0x72, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x12,
	0x3d, 0x0a, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x69, 0x78, 0x69, 0x6e, 0x2e, 0x71, 0x71, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x69, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x65,
	0x73, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x1a, 0x54,
	0x0a, 0x05, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x61, 0x69, 0x6c, 0x79,
	0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x64, 0x61,
	0x69, 0x6c, 0x79, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x75, 0x73, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65,
	0x6d, 0x61, 0x69, 0x6e, 0x22, 0x87, 0x01, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x52, 0x69, 0x64, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x39, 0x0a, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65,
	0x69, 0x78, 0x69, 0x6e, 0x2e, 0x71, 0x71, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x69, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x1a, 0x18, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x69, 0x64, 0x22, 0xd6,
	0x02, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x52, 0x69, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72,
	0x72, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6d,
	0x73, 0x67, 0x12, 0x42, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x69, 0x78, 0x69, 0x6e,
	0x2e, 0x71, 0x71, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x69, 0x64, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0xce, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x69, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x0a, 0x63, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x5f, 0x6d,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x4d,
	0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x55,
	0x72, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x62, 0x6f,
	0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x70, 0x22, 0x45, 0x0a, 0x0f, 0x43, 0x6c, 0x65, 0x61, 0x72,
	0x51, 0x75, 0x6f, 0x74, 0x61, 0x56, 0x32, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70,
	0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x69, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x61, 0x70, 0x70, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x70, 0x70, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x22, 0x43,
	0x0a, 0x0f, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x56, 0x32, 0x52, 0x65,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65,
	0x72, 0x72, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72,
	0x6d, 0x73, 0x67, 0x32, 0xcf, 0x04, 0x0a, 0x0b, 0x4d, 0x67, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x90, 0x01, 0x0a, 0x0a, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x51, 0x75, 0x6f,
	0x74, 0x61, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x69, 0x78, 0x69, 0x6e, 0x2e,
	0x71, 0x71, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x51, 0x75, 0x6f, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x69, 0x78, 0x69,
	0x6e, 0x2e, 0x71, 0x71, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x51, 0x75,
	0x6f, 0x74, 0x61, 0x52, 0x65, 0x73, 0x22, 0x3e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x38, 0x22, 0x30,
	0x2f, 0x63, 0x67, 0x69, 0x2d, 0x62, 0x69, 0x6e, 0x2f, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x5f, 0x71,
	0x75, 0x6f, 0x74, 0x61, 0x3f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x3d, 0x7b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x7d,
	0x3a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x99, 0x01, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41, 0x70,
	0x69, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x69,
	0x78, 0x69, 0x6e, 0x2e, 0x71, 0x71, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70,
	0x69, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x77, 0x65, 0x69, 0x78, 0x69, 0x6e, 0x2e, 0x71, 0x71, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x70, 0x69, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x73, 0x22, 0x44, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x3e, 0x22, 0x36, 0x2f, 0x63, 0x67, 0x69, 0x2d, 0x62, 0x69, 0x6e, 0x2f, 0x6f,
	0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2f, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x2f, 0x67, 0x65, 0x74,
	0x3f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x3d, 0x7b, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x7d, 0x3a, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x12, 0x94, 0x01, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x69, 0x64, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x69, 0x78, 0x69, 0x6e, 0x2e, 0x71,
	0x71, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x69, 0x64, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x69, 0x78, 0x69, 0x6e,
	0x2e, 0x71, 0x71, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x69, 0x64, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x22, 0x42, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x3c, 0x22, 0x34, 0x2f,
	0x63, 0x67, 0x69, 0x2d, 0x62, 0x69, 0x6e, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2f,
	0x72, 0x69, 0x64, 0x2f, 0x67, 0x65, 0x74, 0x3f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x3d, 0x7b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x7d, 0x3a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x7a, 0x0a, 0x0c, 0x43, 0x6c, 0x65,
	0x61, 0x72, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x56, 0x32, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x77, 0x65, 0x69, 0x78, 0x69, 0x6e, 0x2e, 0x71, 0x71, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x43, 0x6c,
	0x65, 0x61, 0x72, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x56, 0x32, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x69, 0x78, 0x69, 0x6e, 0x2e, 0x71, 0x71, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x56, 0x32, 0x52, 0x65,
	0x73, 0x22, 0x22, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1c, 0x22, 0x17, 0x2f, 0x63, 0x67, 0x69, 0x2d,
	0x62, 0x69, 0x6e, 0x2f, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x5f, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x2f,
	0x76, 0x32, 0x3a, 0x01, 0x2a, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x76, 0x2d, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2f,
	0x77, 0x78, 0x2d, 0x6d, 0x69, 0x6e, 0x69, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wx_miniprogram_mgnt_proto_rawDescOnce sync.Once
	file_wx_miniprogram_mgnt_proto_rawDescData = file_wx_miniprogram_mgnt_proto_rawDesc
)

func file_wx_miniprogram_mgnt_proto_rawDescGZIP() []byte {
	file_wx_miniprogram_mgnt_proto_rawDescOnce.Do(func() {
		file_wx_miniprogram_mgnt_proto_rawDescData = protoimpl.X.CompressGZIP(file_wx_miniprogram_mgnt_proto_rawDescData)
	})
	return file_wx_miniprogram_mgnt_proto_rawDescData
}

var file_wx_miniprogram_mgnt_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_wx_miniprogram_mgnt_proto_goTypes = []interface{}{
	(*ClearQuotaData)(nil),        // 0: api.weixin.qq.com.ClearQuotaData
	(*ClearQuotaReq)(nil),         // 1: api.weixin.qq.com.ClearQuotaReq
	(*ClearQuotaRes)(nil),         // 2: api.weixin.qq.com.ClearQuotaRes
	(*GetApiQuotaReq)(nil),        // 3: api.weixin.qq.com.GetApiQuotaReq
	(*GetApiQuotaRes)(nil),        // 4: api.weixin.qq.com.GetApiQuotaRes
	(*GetRidInfoReq)(nil),         // 5: api.weixin.qq.com.GetRidInfoReq
	(*GetRidInfoRes)(nil),         // 6: api.weixin.qq.com.GetRidInfoRes
	(*ClearQuotaV2Req)(nil),       // 7: api.weixin.qq.com.ClearQuotaV2Req
	(*ClearQuotaV2Res)(nil),       // 8: api.weixin.qq.com.ClearQuotaV2Res
	(*ClearQuotaReq_Body)(nil),    // 9: api.weixin.qq.com.ClearQuotaReq.Body
	(*GetApiQuotaReq_Body)(nil),   // 10: api.weixin.qq.com.GetApiQuotaReq.Body
	(*GetApiQuotaRes_Quota)(nil),  // 11: api.weixin.qq.com.GetApiQuotaRes.Quota
	(*GetRidInfoReq_Body)(nil),    // 12: api.weixin.qq.com.GetRidInfoReq.Body
	(*GetRidInfoRes_Request)(nil), // 13: api.weixin.qq.com.GetRidInfoRes.Request
}
var file_wx_miniprogram_mgnt_proto_depIdxs = []int32{
	9,  // 0: api.weixin.qq.com.ClearQuotaReq.body:type_name -> api.weixin.qq.com.ClearQuotaReq.Body
	10, // 1: api.weixin.qq.com.GetApiQuotaReq.body:type_name -> api.weixin.qq.com.GetApiQuotaReq.Body
	11, // 2: api.weixin.qq.com.GetApiQuotaRes.quota:type_name -> api.weixin.qq.com.GetApiQuotaRes.Quota
	12, // 3: api.weixin.qq.com.GetRidInfoReq.body:type_name -> api.weixin.qq.com.GetRidInfoReq.Body
	13, // 4: api.weixin.qq.com.GetRidInfoRes.request:type_name -> api.weixin.qq.com.GetRidInfoRes.Request
	1,  // 5: api.weixin.qq.com.MgntService.ClearQuota:input_type -> api.weixin.qq.com.ClearQuotaReq
	3,  // 6: api.weixin.qq.com.MgntService.GetApiQuota:input_type -> api.weixin.qq.com.GetApiQuotaReq
	5,  // 7: api.weixin.qq.com.MgntService.GetRidInfo:input_type -> api.weixin.qq.com.GetRidInfoReq
	7,  // 8: api.weixin.qq.com.MgntService.ClearQuotaV2:input_type -> api.weixin.qq.com.ClearQuotaV2Req
	2,  // 9: api.weixin.qq.com.MgntService.ClearQuota:output_type -> api.weixin.qq.com.ClearQuotaRes
	4,  // 10: api.weixin.qq.com.MgntService.GetApiQuota:output_type -> api.weixin.qq.com.GetApiQuotaRes
	6,  // 11: api.weixin.qq.com.MgntService.GetRidInfo:output_type -> api.weixin.qq.com.GetRidInfoRes
	8,  // 12: api.weixin.qq.com.MgntService.ClearQuotaV2:output_type -> api.weixin.qq.com.ClearQuotaV2Res
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_wx_miniprogram_mgnt_proto_init() }
func file_wx_miniprogram_mgnt_proto_init() {
	if File_wx_miniprogram_mgnt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wx_miniprogram_mgnt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearQuotaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wx_miniprogram_mgnt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearQuotaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wx_miniprogram_mgnt_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearQuotaRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wx_miniprogram_mgnt_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetApiQuotaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wx_miniprogram_mgnt_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetApiQuotaRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wx_miniprogram_mgnt_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRidInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wx_miniprogram_mgnt_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRidInfoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wx_miniprogram_mgnt_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearQuotaV2Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wx_miniprogram_mgnt_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearQuotaV2Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wx_miniprogram_mgnt_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearQuotaReq_Body); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wx_miniprogram_mgnt_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetApiQuotaReq_Body); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wx_miniprogram_mgnt_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetApiQuotaRes_Quota); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wx_miniprogram_mgnt_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRidInfoReq_Body); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wx_miniprogram_mgnt_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRidInfoRes_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wx_miniprogram_mgnt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wx_miniprogram_mgnt_proto_goTypes,
		DependencyIndexes: file_wx_miniprogram_mgnt_proto_depIdxs,
		MessageInfos:      file_wx_miniprogram_mgnt_proto_msgTypes,
	}.Build()
	File_wx_miniprogram_mgnt_proto = out.File
	file_wx_miniprogram_mgnt_proto_rawDesc = nil
	file_wx_miniprogram_mgnt_proto_goTypes = nil
	file_wx_miniprogram_mgnt_proto_depIdxs = nil
}
