// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wx-miniprogram/qrcode.proto

package wx_miniprogram // import "github.com/dev-openapi/wx-miniprogram"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LineColor struct {
	R                    int32    `protobuf:"varint,1,opt,name=r" json:"r,omitempty"`
	G                    int32    `protobuf:"varint,2,opt,name=g" json:"g,omitempty"`
	B                    int32    `protobuf:"varint,3,opt,name=b" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LineColor) Reset()         { *m = LineColor{} }
func (m *LineColor) String() string { return proto.CompactTextString(m) }
func (*LineColor) ProtoMessage()    {}
func (*LineColor) Descriptor() ([]byte, []int) {
	return fileDescriptor_qrcode_0af10a96e6285168, []int{0}
}
func (m *LineColor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LineColor.Unmarshal(m, b)
}
func (m *LineColor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LineColor.Marshal(b, m, deterministic)
}
func (dst *LineColor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LineColor.Merge(dst, src)
}
func (m *LineColor) XXX_Size() int {
	return xxx_messageInfo_LineColor.Size(m)
}
func (m *LineColor) XXX_DiscardUnknown() {
	xxx_messageInfo_LineColor.DiscardUnknown(m)
}

var xxx_messageInfo_LineColor proto.InternalMessageInfo

func (m *LineColor) GetR() int32 {
	if m != nil {
		return m.R
	}
	return 0
}

func (m *LineColor) GetG() int32 {
	if m != nil {
		return m.G
	}
	return 0
}

func (m *LineColor) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

type GetQrcodeReq struct {
	AccessToken          string             `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	Body                 *GetQrcodeReq_Body `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetQrcodeReq) Reset()         { *m = GetQrcodeReq{} }
func (m *GetQrcodeReq) String() string { return proto.CompactTextString(m) }
func (*GetQrcodeReq) ProtoMessage()    {}
func (*GetQrcodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_qrcode_0af10a96e6285168, []int{1}
}
func (m *GetQrcodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQrcodeReq.Unmarshal(m, b)
}
func (m *GetQrcodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQrcodeReq.Marshal(b, m, deterministic)
}
func (dst *GetQrcodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQrcodeReq.Merge(dst, src)
}
func (m *GetQrcodeReq) XXX_Size() int {
	return xxx_messageInfo_GetQrcodeReq.Size(m)
}
func (m *GetQrcodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQrcodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetQrcodeReq proto.InternalMessageInfo

func (m *GetQrcodeReq) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GetQrcodeReq) GetBody() *GetQrcodeReq_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type GetQrcodeReq_Body struct {
	Path                 string     `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Width                int32      `protobuf:"varint,2,opt,name=width" json:"width,omitempty"`
	AutoColor            bool       `protobuf:"varint,3,opt,name=auto_color,json=autoColor" json:"auto_color,omitempty"`
	LineColor            *LineColor `protobuf:"bytes,4,opt,name=line_color,json=lineColor" json:"line_color,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetQrcodeReq_Body) Reset()         { *m = GetQrcodeReq_Body{} }
func (m *GetQrcodeReq_Body) String() string { return proto.CompactTextString(m) }
func (*GetQrcodeReq_Body) ProtoMessage()    {}
func (*GetQrcodeReq_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_qrcode_0af10a96e6285168, []int{1, 0}
}
func (m *GetQrcodeReq_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQrcodeReq_Body.Unmarshal(m, b)
}
func (m *GetQrcodeReq_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQrcodeReq_Body.Marshal(b, m, deterministic)
}
func (dst *GetQrcodeReq_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQrcodeReq_Body.Merge(dst, src)
}
func (m *GetQrcodeReq_Body) XXX_Size() int {
	return xxx_messageInfo_GetQrcodeReq_Body.Size(m)
}
func (m *GetQrcodeReq_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQrcodeReq_Body.DiscardUnknown(m)
}

var xxx_messageInfo_GetQrcodeReq_Body proto.InternalMessageInfo

func (m *GetQrcodeReq_Body) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *GetQrcodeReq_Body) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *GetQrcodeReq_Body) GetAutoColor() bool {
	if m != nil {
		return m.AutoColor
	}
	return false
}

func (m *GetQrcodeReq_Body) GetLineColor() *LineColor {
	if m != nil {
		return m.LineColor
	}
	return nil
}

type GetQrcodeRes struct {
	Errcode              int32    `protobuf:"varint,1,opt,name=errcode" json:"errcode,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg" json:"errmsg,omitempty"`
	Buffer               []byte   `protobuf:"bytes,3,opt,name=buffer,proto3" json:"buffer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetQrcodeRes) Reset()         { *m = GetQrcodeRes{} }
func (m *GetQrcodeRes) String() string { return proto.CompactTextString(m) }
func (*GetQrcodeRes) ProtoMessage()    {}
func (*GetQrcodeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_qrcode_0af10a96e6285168, []int{2}
}
func (m *GetQrcodeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQrcodeRes.Unmarshal(m, b)
}
func (m *GetQrcodeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQrcodeRes.Marshal(b, m, deterministic)
}
func (dst *GetQrcodeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQrcodeRes.Merge(dst, src)
}
func (m *GetQrcodeRes) XXX_Size() int {
	return xxx_messageInfo_GetQrcodeRes.Size(m)
}
func (m *GetQrcodeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQrcodeRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetQrcodeRes proto.InternalMessageInfo

func (m *GetQrcodeRes) GetErrcode() int32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *GetQrcodeRes) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *GetQrcodeRes) GetBuffer() []byte {
	if m != nil {
		return m.Buffer
	}
	return nil
}

type GetUnlimitedQrcodeReq struct {
	AccessToken          string                      `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	Body                 *GetUnlimitedQrcodeReq_Body `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *GetUnlimitedQrcodeReq) Reset()         { *m = GetUnlimitedQrcodeReq{} }
func (m *GetUnlimitedQrcodeReq) String() string { return proto.CompactTextString(m) }
func (*GetUnlimitedQrcodeReq) ProtoMessage()    {}
func (*GetUnlimitedQrcodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_qrcode_0af10a96e6285168, []int{3}
}
func (m *GetUnlimitedQrcodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUnlimitedQrcodeReq.Unmarshal(m, b)
}
func (m *GetUnlimitedQrcodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUnlimitedQrcodeReq.Marshal(b, m, deterministic)
}
func (dst *GetUnlimitedQrcodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUnlimitedQrcodeReq.Merge(dst, src)
}
func (m *GetUnlimitedQrcodeReq) XXX_Size() int {
	return xxx_messageInfo_GetUnlimitedQrcodeReq.Size(m)
}
func (m *GetUnlimitedQrcodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUnlimitedQrcodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUnlimitedQrcodeReq proto.InternalMessageInfo

func (m *GetUnlimitedQrcodeReq) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GetUnlimitedQrcodeReq) GetBody() *GetUnlimitedQrcodeReq_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type GetUnlimitedQrcodeReq_Body struct {
	Scene                string     `protobuf:"bytes,1,opt,name=scene" json:"scene,omitempty"`
	Page                 string     `protobuf:"bytes,2,opt,name=page" json:"page,omitempty"`
	CheckPath            bool       `protobuf:"varint,3,opt,name=check_path,json=checkPath" json:"check_path,omitempty"`
	EnvVersion           string     `protobuf:"bytes,4,opt,name=env_version,json=envVersion" json:"env_version,omitempty"`
	Width                int32      `protobuf:"varint,5,opt,name=width" json:"width,omitempty"`
	AutoColor            bool       `protobuf:"varint,6,opt,name=auto_color,json=autoColor" json:"auto_color,omitempty"`
	LineColor            *LineColor `protobuf:"bytes,7,opt,name=line_color,json=lineColor" json:"line_color,omitempty"`
	IsHyaline            bool       `protobuf:"varint,8,opt,name=is_hyaline,json=isHyaline" json:"is_hyaline,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetUnlimitedQrcodeReq_Body) Reset()         { *m = GetUnlimitedQrcodeReq_Body{} }
func (m *GetUnlimitedQrcodeReq_Body) String() string { return proto.CompactTextString(m) }
func (*GetUnlimitedQrcodeReq_Body) ProtoMessage()    {}
func (*GetUnlimitedQrcodeReq_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_qrcode_0af10a96e6285168, []int{3, 0}
}
func (m *GetUnlimitedQrcodeReq_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUnlimitedQrcodeReq_Body.Unmarshal(m, b)
}
func (m *GetUnlimitedQrcodeReq_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUnlimitedQrcodeReq_Body.Marshal(b, m, deterministic)
}
func (dst *GetUnlimitedQrcodeReq_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUnlimitedQrcodeReq_Body.Merge(dst, src)
}
func (m *GetUnlimitedQrcodeReq_Body) XXX_Size() int {
	return xxx_messageInfo_GetUnlimitedQrcodeReq_Body.Size(m)
}
func (m *GetUnlimitedQrcodeReq_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUnlimitedQrcodeReq_Body.DiscardUnknown(m)
}

var xxx_messageInfo_GetUnlimitedQrcodeReq_Body proto.InternalMessageInfo

func (m *GetUnlimitedQrcodeReq_Body) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *GetUnlimitedQrcodeReq_Body) GetPage() string {
	if m != nil {
		return m.Page
	}
	return ""
}

func (m *GetUnlimitedQrcodeReq_Body) GetCheckPath() bool {
	if m != nil {
		return m.CheckPath
	}
	return false
}

func (m *GetUnlimitedQrcodeReq_Body) GetEnvVersion() string {
	if m != nil {
		return m.EnvVersion
	}
	return ""
}

func (m *GetUnlimitedQrcodeReq_Body) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *GetUnlimitedQrcodeReq_Body) GetAutoColor() bool {
	if m != nil {
		return m.AutoColor
	}
	return false
}

func (m *GetUnlimitedQrcodeReq_Body) GetLineColor() *LineColor {
	if m != nil {
		return m.LineColor
	}
	return nil
}

func (m *GetUnlimitedQrcodeReq_Body) GetIsHyaline() bool {
	if m != nil {
		return m.IsHyaline
	}
	return false
}

type GetUnlimitedQrcodeRes struct {
	Errcode              int32    `protobuf:"varint,1,opt,name=errcode" json:"errcode,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg" json:"errmsg,omitempty"`
	Buffer               []byte   `protobuf:"bytes,3,opt,name=buffer,proto3" json:"buffer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUnlimitedQrcodeRes) Reset()         { *m = GetUnlimitedQrcodeRes{} }
func (m *GetUnlimitedQrcodeRes) String() string { return proto.CompactTextString(m) }
func (*GetUnlimitedQrcodeRes) ProtoMessage()    {}
func (*GetUnlimitedQrcodeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_qrcode_0af10a96e6285168, []int{4}
}
func (m *GetUnlimitedQrcodeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUnlimitedQrcodeRes.Unmarshal(m, b)
}
func (m *GetUnlimitedQrcodeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUnlimitedQrcodeRes.Marshal(b, m, deterministic)
}
func (dst *GetUnlimitedQrcodeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUnlimitedQrcodeRes.Merge(dst, src)
}
func (m *GetUnlimitedQrcodeRes) XXX_Size() int {
	return xxx_messageInfo_GetUnlimitedQrcodeRes.Size(m)
}
func (m *GetUnlimitedQrcodeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUnlimitedQrcodeRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetUnlimitedQrcodeRes proto.InternalMessageInfo

func (m *GetUnlimitedQrcodeRes) GetErrcode() int32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *GetUnlimitedQrcodeRes) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *GetUnlimitedQrcodeRes) GetBuffer() []byte {
	if m != nil {
		return m.Buffer
	}
	return nil
}

type CreateQrcodeReq struct {
	AccessToken          string                `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	Body                 *CreateQrcodeReq_Body `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateQrcodeReq) Reset()         { *m = CreateQrcodeReq{} }
func (m *CreateQrcodeReq) String() string { return proto.CompactTextString(m) }
func (*CreateQrcodeReq) ProtoMessage()    {}
func (*CreateQrcodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_qrcode_0af10a96e6285168, []int{5}
}
func (m *CreateQrcodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateQrcodeReq.Unmarshal(m, b)
}
func (m *CreateQrcodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateQrcodeReq.Marshal(b, m, deterministic)
}
func (dst *CreateQrcodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateQrcodeReq.Merge(dst, src)
}
func (m *CreateQrcodeReq) XXX_Size() int {
	return xxx_messageInfo_CreateQrcodeReq.Size(m)
}
func (m *CreateQrcodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateQrcodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateQrcodeReq proto.InternalMessageInfo

func (m *CreateQrcodeReq) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *CreateQrcodeReq) GetBody() *CreateQrcodeReq_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type CreateQrcodeReq_Body struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Width                string   `protobuf:"bytes,2,opt,name=width" json:"width,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateQrcodeReq_Body) Reset()         { *m = CreateQrcodeReq_Body{} }
func (m *CreateQrcodeReq_Body) String() string { return proto.CompactTextString(m) }
func (*CreateQrcodeReq_Body) ProtoMessage()    {}
func (*CreateQrcodeReq_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_qrcode_0af10a96e6285168, []int{5, 0}
}
func (m *CreateQrcodeReq_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateQrcodeReq_Body.Unmarshal(m, b)
}
func (m *CreateQrcodeReq_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateQrcodeReq_Body.Marshal(b, m, deterministic)
}
func (dst *CreateQrcodeReq_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateQrcodeReq_Body.Merge(dst, src)
}
func (m *CreateQrcodeReq_Body) XXX_Size() int {
	return xxx_messageInfo_CreateQrcodeReq_Body.Size(m)
}
func (m *CreateQrcodeReq_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateQrcodeReq_Body.DiscardUnknown(m)
}

var xxx_messageInfo_CreateQrcodeReq_Body proto.InternalMessageInfo

func (m *CreateQrcodeReq_Body) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *CreateQrcodeReq_Body) GetWidth() string {
	if m != nil {
		return m.Width
	}
	return ""
}

type CreateQrcodeRes struct {
	Errcode              int32    `protobuf:"varint,1,opt,name=errcode" json:"errcode,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg" json:"errmsg,omitempty"`
	Buffer               []byte   `protobuf:"bytes,3,opt,name=buffer,proto3" json:"buffer,omitempty"`
	ContentType          string   `protobuf:"bytes,4,opt,name=contentType" json:"contentType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateQrcodeRes) Reset()         { *m = CreateQrcodeRes{} }
func (m *CreateQrcodeRes) String() string { return proto.CompactTextString(m) }
func (*CreateQrcodeRes) ProtoMessage()    {}
func (*CreateQrcodeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_qrcode_0af10a96e6285168, []int{6}
}
func (m *CreateQrcodeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateQrcodeRes.Unmarshal(m, b)
}
func (m *CreateQrcodeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateQrcodeRes.Marshal(b, m, deterministic)
}
func (dst *CreateQrcodeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateQrcodeRes.Merge(dst, src)
}
func (m *CreateQrcodeRes) XXX_Size() int {
	return xxx_messageInfo_CreateQrcodeRes.Size(m)
}
func (m *CreateQrcodeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateQrcodeRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateQrcodeRes proto.InternalMessageInfo

func (m *CreateQrcodeRes) GetErrcode() int32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *CreateQrcodeRes) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *CreateQrcodeRes) GetBuffer() []byte {
	if m != nil {
		return m.Buffer
	}
	return nil
}

func (m *CreateQrcodeRes) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

type QuerySchemeReq struct {
	AccessToken          string               `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	Body                 *QuerySchemeReq_Body `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *QuerySchemeReq) Reset()         { *m = QuerySchemeReq{} }
func (m *QuerySchemeReq) String() string { return proto.CompactTextString(m) }
func (*QuerySchemeReq) ProtoMessage()    {}
func (*QuerySchemeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_qrcode_0af10a96e6285168, []int{7}
}
func (m *QuerySchemeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuerySchemeReq.Unmarshal(m, b)
}
func (m *QuerySchemeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuerySchemeReq.Marshal(b, m, deterministic)
}
func (dst *QuerySchemeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySchemeReq.Merge(dst, src)
}
func (m *QuerySchemeReq) XXX_Size() int {
	return xxx_messageInfo_QuerySchemeReq.Size(m)
}
func (m *QuerySchemeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySchemeReq.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySchemeReq proto.InternalMessageInfo

func (m *QuerySchemeReq) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *QuerySchemeReq) GetBody() *QuerySchemeReq_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type QuerySchemeReq_Body struct {
	Scheme               string   `protobuf:"bytes,1,opt,name=scheme" json:"scheme,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuerySchemeReq_Body) Reset()         { *m = QuerySchemeReq_Body{} }
func (m *QuerySchemeReq_Body) String() string { return proto.CompactTextString(m) }
func (*QuerySchemeReq_Body) ProtoMessage()    {}
func (*QuerySchemeReq_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_qrcode_0af10a96e6285168, []int{7, 0}
}
func (m *QuerySchemeReq_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuerySchemeReq_Body.Unmarshal(m, b)
}
func (m *QuerySchemeReq_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuerySchemeReq_Body.Marshal(b, m, deterministic)
}
func (dst *QuerySchemeReq_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySchemeReq_Body.Merge(dst, src)
}
func (m *QuerySchemeReq_Body) XXX_Size() int {
	return xxx_messageInfo_QuerySchemeReq_Body.Size(m)
}
func (m *QuerySchemeReq_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySchemeReq_Body.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySchemeReq_Body proto.InternalMessageInfo

func (m *QuerySchemeReq_Body) GetScheme() string {
	if m != nil {
		return m.Scheme
	}
	return ""
}

type SchemeInfo struct {
	Appid                string   `protobuf:"bytes,1,opt,name=appid" json:"appid,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Query                string   `protobuf:"bytes,3,opt,name=query" json:"query,omitempty"`
	CreateTime           int64    `protobuf:"varint,4,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	ExpireTime           int64    `protobuf:"varint,5,opt,name=expire_time,json=expireTime" json:"expire_time,omitempty"`
	EnvVersion           string   `protobuf:"bytes,6,opt,name=env_version,json=envVersion" json:"env_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchemeInfo) Reset()         { *m = SchemeInfo{} }
func (m *SchemeInfo) String() string { return proto.CompactTextString(m) }
func (*SchemeInfo) ProtoMessage()    {}
func (*SchemeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_qrcode_0af10a96e6285168, []int{8}
}
func (m *SchemeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemeInfo.Unmarshal(m, b)
}
func (m *SchemeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemeInfo.Marshal(b, m, deterministic)
}
func (dst *SchemeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemeInfo.Merge(dst, src)
}
func (m *SchemeInfo) XXX_Size() int {
	return xxx_messageInfo_SchemeInfo.Size(m)
}
func (m *SchemeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SchemeInfo proto.InternalMessageInfo

func (m *SchemeInfo) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *SchemeInfo) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *SchemeInfo) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SchemeInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *SchemeInfo) GetExpireTime() int64 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

func (m *SchemeInfo) GetEnvVersion() string {
	if m != nil {
		return m.EnvVersion
	}
	return ""
}

type QuerySchemeRes struct {
	Errcode              int32       `protobuf:"varint,1,opt,name=errcode" json:"errcode,omitempty"`
	Errmsg               string      `protobuf:"bytes,2,opt,name=errmsg" json:"errmsg,omitempty"`
	SchemeInfo           *SchemeInfo `protobuf:"bytes,3,opt,name=scheme_info,json=schemeInfo" json:"scheme_info,omitempty"`
	VisitOpenid          string      `protobuf:"bytes,4,opt,name=visit_openid,json=visitOpenid" json:"visit_openid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *QuerySchemeRes) Reset()         { *m = QuerySchemeRes{} }
func (m *QuerySchemeRes) String() string { return proto.CompactTextString(m) }
func (*QuerySchemeRes) ProtoMessage()    {}
func (*QuerySchemeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_qrcode_0af10a96e6285168, []int{9}
}
func (m *QuerySchemeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuerySchemeRes.Unmarshal(m, b)
}
func (m *QuerySchemeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuerySchemeRes.Marshal(b, m, deterministic)
}
func (dst *QuerySchemeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySchemeRes.Merge(dst, src)
}
func (m *QuerySchemeRes) XXX_Size() int {
	return xxx_messageInfo_QuerySchemeRes.Size(m)
}
func (m *QuerySchemeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySchemeRes.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySchemeRes proto.InternalMessageInfo

func (m *QuerySchemeRes) GetErrcode() int32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *QuerySchemeRes) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *QuerySchemeRes) GetSchemeInfo() *SchemeInfo {
	if m != nil {
		return m.SchemeInfo
	}
	return nil
}

func (m *QuerySchemeRes) GetVisitOpenid() string {
	if m != nil {
		return m.VisitOpenid
	}
	return ""
}

type JumpWxa struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Query                string   `protobuf:"bytes,2,opt,name=query" json:"query,omitempty"`
	EnvVersion           string   `protobuf:"bytes,3,opt,name=env_version,json=envVersion" json:"env_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JumpWxa) Reset()         { *m = JumpWxa{} }
func (m *JumpWxa) String() string { return proto.CompactTextString(m) }
func (*JumpWxa) ProtoMessage()    {}
func (*JumpWxa) Descriptor() ([]byte, []int) {
	return fileDescriptor_qrcode_0af10a96e6285168, []int{10}
}
func (m *JumpWxa) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JumpWxa.Unmarshal(m, b)
}
func (m *JumpWxa) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JumpWxa.Marshal(b, m, deterministic)
}
func (dst *JumpWxa) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JumpWxa.Merge(dst, src)
}
func (m *JumpWxa) XXX_Size() int {
	return xxx_messageInfo_JumpWxa.Size(m)
}
func (m *JumpWxa) XXX_DiscardUnknown() {
	xxx_messageInfo_JumpWxa.DiscardUnknown(m)
}

var xxx_messageInfo_JumpWxa proto.InternalMessageInfo

func (m *JumpWxa) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *JumpWxa) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *JumpWxa) GetEnvVersion() string {
	if m != nil {
		return m.EnvVersion
	}
	return ""
}

type GenerateSchemeReq struct {
	AccessToken          string                  `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	Body                 *GenerateSchemeReq_Body `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GenerateSchemeReq) Reset()         { *m = GenerateSchemeReq{} }
func (m *GenerateSchemeReq) String() string { return proto.CompactTextString(m) }
func (*GenerateSchemeReq) ProtoMessage()    {}
func (*GenerateSchemeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_qrcode_0af10a96e6285168, []int{11}
}
func (m *GenerateSchemeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateSchemeReq.Unmarshal(m, b)
}
func (m *GenerateSchemeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateSchemeReq.Marshal(b, m, deterministic)
}
func (dst *GenerateSchemeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateSchemeReq.Merge(dst, src)
}
func (m *GenerateSchemeReq) XXX_Size() int {
	return xxx_messageInfo_GenerateSchemeReq.Size(m)
}
func (m *GenerateSchemeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateSchemeReq.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateSchemeReq proto.InternalMessageInfo

func (m *GenerateSchemeReq) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GenerateSchemeReq) GetBody() *GenerateSchemeReq_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type GenerateSchemeReq_Body struct {
	JumpWxa              *JumpWxa `protobuf:"bytes,1,opt,name=jump_wxa,json=jumpWxa" json:"jump_wxa,omitempty"`
	IsExpire             bool     `protobuf:"varint,2,opt,name=is_expire,json=isExpire" json:"is_expire,omitempty"`
	ExpireTime           int64    `protobuf:"varint,3,opt,name=expire_time,json=expireTime" json:"expire_time,omitempty"`
	ExpireType           int32    `protobuf:"varint,4,opt,name=expire_type,json=expireType" json:"expire_type,omitempty"`
	ExpireInterval       int64    `protobuf:"varint,5,opt,name=expire_interval,json=expireInterval" json:"expire_interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateSchemeReq_Body) Reset()         { *m = GenerateSchemeReq_Body{} }
func (m *GenerateSchemeReq_Body) String() string { return proto.CompactTextString(m) }
func (*GenerateSchemeReq_Body) ProtoMessage()    {}
func (*GenerateSchemeReq_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_qrcode_0af10a96e6285168, []int{11, 0}
}
func (m *GenerateSchemeReq_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateSchemeReq_Body.Unmarshal(m, b)
}
func (m *GenerateSchemeReq_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateSchemeReq_Body.Marshal(b, m, deterministic)
}
func (dst *GenerateSchemeReq_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateSchemeReq_Body.Merge(dst, src)
}
func (m *GenerateSchemeReq_Body) XXX_Size() int {
	return xxx_messageInfo_GenerateSchemeReq_Body.Size(m)
}
func (m *GenerateSchemeReq_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateSchemeReq_Body.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateSchemeReq_Body proto.InternalMessageInfo

func (m *GenerateSchemeReq_Body) GetJumpWxa() *JumpWxa {
	if m != nil {
		return m.JumpWxa
	}
	return nil
}

func (m *GenerateSchemeReq_Body) GetIsExpire() bool {
	if m != nil {
		return m.IsExpire
	}
	return false
}

func (m *GenerateSchemeReq_Body) GetExpireTime() int64 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

func (m *GenerateSchemeReq_Body) GetExpireType() int32 {
	if m != nil {
		return m.ExpireType
	}
	return 0
}

func (m *GenerateSchemeReq_Body) GetExpireInterval() int64 {
	if m != nil {
		return m.ExpireInterval
	}
	return 0
}

type GenerateSchemeRes struct {
	Errcode              int32    `protobuf:"varint,1,opt,name=errcode" json:"errcode,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg" json:"errmsg,omitempty"`
	Openlink             string   `protobuf:"bytes,3,opt,name=openlink" json:"openlink,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateSchemeRes) Reset()         { *m = GenerateSchemeRes{} }
func (m *GenerateSchemeRes) String() string { return proto.CompactTextString(m) }
func (*GenerateSchemeRes) ProtoMessage()    {}
func (*GenerateSchemeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_qrcode_0af10a96e6285168, []int{12}
}
func (m *GenerateSchemeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateSchemeRes.Unmarshal(m, b)
}
func (m *GenerateSchemeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateSchemeRes.Marshal(b, m, deterministic)
}
func (dst *GenerateSchemeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateSchemeRes.Merge(dst, src)
}
func (m *GenerateSchemeRes) XXX_Size() int {
	return xxx_messageInfo_GenerateSchemeRes.Size(m)
}
func (m *GenerateSchemeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateSchemeRes.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateSchemeRes proto.InternalMessageInfo

func (m *GenerateSchemeRes) GetErrcode() int32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *GenerateSchemeRes) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *GenerateSchemeRes) GetOpenlink() string {
	if m != nil {
		return m.Openlink
	}
	return ""
}

func init() {
	proto.RegisterType((*LineColor)(nil), "api.weixin.qq.com.LineColor")
	proto.RegisterType((*GetQrcodeReq)(nil), "api.weixin.qq.com.GetQrcodeReq")
	proto.RegisterType((*GetQrcodeReq_Body)(nil), "api.weixin.qq.com.GetQrcodeReq.Body")
	proto.RegisterType((*GetQrcodeRes)(nil), "api.weixin.qq.com.GetQrcodeRes")
	proto.RegisterType((*GetUnlimitedQrcodeReq)(nil), "api.weixin.qq.com.GetUnlimitedQrcodeReq")
	proto.RegisterType((*GetUnlimitedQrcodeReq_Body)(nil), "api.weixin.qq.com.GetUnlimitedQrcodeReq.Body")
	proto.RegisterType((*GetUnlimitedQrcodeRes)(nil), "api.weixin.qq.com.GetUnlimitedQrcodeRes")
	proto.RegisterType((*CreateQrcodeReq)(nil), "api.weixin.qq.com.CreateQrcodeReq")
	proto.RegisterType((*CreateQrcodeReq_Body)(nil), "api.weixin.qq.com.CreateQrcodeReq.Body")
	proto.RegisterType((*CreateQrcodeRes)(nil), "api.weixin.qq.com.CreateQrcodeRes")
	proto.RegisterType((*QuerySchemeReq)(nil), "api.weixin.qq.com.QuerySchemeReq")
	proto.RegisterType((*QuerySchemeReq_Body)(nil), "api.weixin.qq.com.QuerySchemeReq.Body")
	proto.RegisterType((*SchemeInfo)(nil), "api.weixin.qq.com.SchemeInfo")
	proto.RegisterType((*QuerySchemeRes)(nil), "api.weixin.qq.com.QuerySchemeRes")
	proto.RegisterType((*JumpWxa)(nil), "api.weixin.qq.com.JumpWxa")
	proto.RegisterType((*GenerateSchemeReq)(nil), "api.weixin.qq.com.GenerateSchemeReq")
	proto.RegisterType((*GenerateSchemeReq_Body)(nil), "api.weixin.qq.com.GenerateSchemeReq.Body")
	proto.RegisterType((*GenerateSchemeRes)(nil), "api.weixin.qq.com.GenerateSchemeRes")
}

func init() {
	proto.RegisterFile("wx-miniprogram/qrcode.proto", fileDescriptor_qrcode_0af10a96e6285168)
}

var fileDescriptor_qrcode_0af10a96e6285168 = []byte{
	// 1024 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x4d, 0x6f, 0x1b, 0x45,
	0x18, 0xd6, 0xda, 0xb1, 0xe3, 0x7d, 0x6d, 0x52, 0x75, 0x54, 0x2a, 0xcb, 0x6d, 0x69, 0x33, 0x2a,
	0xa4, 0x08, 0x62, 0xa3, 0x94, 0x0a, 0x48, 0x14, 0x3e, 0x1a, 0xa1, 0x10, 0x84, 0x04, 0xdd, 0x86,
	0x0f, 0x71, 0x59, 0x8d, 0xd7, 0x6f, 0xec, 0x69, 0xbc, 0x33, 0xeb, 0xdd, 0xf5, 0x97, 0x50, 0x0f,
	0xe5, 0xc4, 0x01, 0xa9, 0x07, 0x8e, 0x3d, 0x21, 0xc4, 0x85, 0x0b, 0xbf, 0x80, 0x23, 0xbf, 0x80,
	0xbf, 0xc0, 0xaf, 0xe0, 0x84, 0x76, 0x66, 0xec, 0xac, 0x3f, 0x5a, 0x6f, 0xaa, 0xdc, 0xfc, 0xbc,
	0xfb, 0xee, 0x3b, 0xcf, 0x3c, 0xcf, 0xfb, 0xce, 0xac, 0xe1, 0xda, 0x70, 0xb4, 0xed, 0x73, 0xc1,
	0x83, 0x50, 0xb6, 0x43, 0xe6, 0x37, 0x7a, 0xa1, 0x27, 0x5b, 0x58, 0x0f, 0x42, 0x19, 0x4b, 0x72,
	0x99, 0x05, 0xbc, 0x3e, 0x44, 0x3e, 0xe2, 0xa2, 0xde, 0xeb, 0xd5, 0x3d, 0xe9, 0xd7, 0xae, 0xb7,
	0xa5, 0x6c, 0x77, 0xb1, 0xc1, 0x02, 0xde, 0x60, 0x42, 0xc8, 0x98, 0xc5, 0x5c, 0x8a, 0x48, 0xbf,
	0x40, 0xef, 0x81, 0xfd, 0x05, 0x17, 0x78, 0x20, 0xbb, 0x32, 0x24, 0x15, 0xb0, 0xc2, 0xaa, 0x75,
	0xcb, 0xba, 0x53, 0x70, 0x2c, 0x85, 0xda, 0xd5, 0x9c, 0x46, 0xed, 0x04, 0x35, 0xab, 0x79, 0x8d,
	0x9a, 0xf4, 0x3f, 0x0b, 0x2a, 0x87, 0x18, 0x3f, 0x50, 0x6b, 0x3b, 0xd8, 0x23, 0x9b, 0x50, 0x61,
	0x9e, 0x87, 0x51, 0xe4, 0xc6, 0xf2, 0x14, 0x85, 0xaa, 0x62, 0x3b, 0x65, 0x1d, 0x3b, 0x4e, 0x42,
	0xe4, 0x7d, 0x58, 0x6b, 0xca, 0xd6, 0x58, 0x95, 0x2c, 0xef, 0xdc, 0xae, 0x2f, 0x50, 0xad, 0xa7,
	0x2b, 0xd6, 0xef, 0xcb, 0xd6, 0xd8, 0x51, 0x6f, 0xd4, 0x7e, 0xb6, 0x60, 0x2d, 0x81, 0x84, 0xc0,
	0x5a, 0xc0, 0xe2, 0x8e, 0xa9, 0xae, 0x7e, 0x93, 0x2b, 0x50, 0x18, 0xf2, 0x56, 0xdc, 0x31, 0x54,
	0x35, 0x20, 0x37, 0x00, 0x58, 0x3f, 0x96, 0xae, 0x97, 0x6c, 0x4c, 0xf1, 0x2e, 0x39, 0x76, 0x12,
	0xd1, 0x3b, 0xdd, 0x03, 0xe8, 0x72, 0x81, 0xe6, 0xf1, 0x9a, 0x62, 0x74, 0x7d, 0x09, 0xa3, 0xa9,
	0x36, 0x8e, 0xdd, 0x9d, 0xfc, 0xa4, 0xdf, 0xcd, 0xec, 0x3d, 0x22, 0x55, 0x58, 0xc7, 0x50, 0x21,
	0x23, 0xde, 0x04, 0x92, 0xab, 0x50, 0xc4, 0x30, 0xf4, 0x23, 0xad, 0xa3, 0xed, 0x18, 0x94, 0xc4,
	0x9b, 0xfd, 0x93, 0x13, 0xd4, 0xcc, 0x2a, 0x8e, 0x41, 0xf4, 0x49, 0x1e, 0x5e, 0x3d, 0xc4, 0xf8,
	0x6b, 0xd1, 0xe5, 0x3e, 0x8f, 0xb1, 0x75, 0x2e, 0x7d, 0x3f, 0x99, 0xd1, 0x77, 0x7b, 0xb9, 0xbe,
	0x8b, 0xa5, 0xd3, 0x42, 0x3f, 0xc9, 0x19, 0xa1, 0xaf, 0x40, 0x21, 0xf2, 0x50, 0xa0, 0x59, 0x47,
	0x03, 0x2d, 0x7f, 0x1b, 0xcd, 0x66, 0xd4, 0xef, 0x44, 0x68, 0xaf, 0x83, 0xde, 0xa9, 0xab, 0x8c,
	0x31, 0x42, 0xab, 0xc8, 0x57, 0x89, 0x3b, 0x37, 0xa1, 0x8c, 0x62, 0xe0, 0x0e, 0x30, 0x8c, 0xb8,
	0x14, 0x4a, 0x69, 0xdb, 0x01, 0x14, 0x83, 0x6f, 0x74, 0xe4, 0xcc, 0xbe, 0xc2, 0xf3, 0xed, 0x2b,
	0xbe, 0xd8, 0xbe, 0xf5, 0x73, 0xd9, 0x97, 0xd4, 0xe6, 0x91, 0xdb, 0x19, 0xb3, 0x24, 0x54, 0x2d,
	0xe9, 0xda, 0x3c, 0xfa, 0x4c, 0x07, 0x28, 0x5b, 0x6e, 0xc1, 0x45, 0xda, 0xfc, 0x9b, 0x05, 0x97,
	0x0e, 0x42, 0x64, 0x31, 0x9e, 0xcb, 0xe0, 0x3d, 0x63, 0x70, 0x5e, 0xed, 0x77, 0x6b, 0xc9, 0x7e,
	0xe7, 0x8a, 0xa6, 0xad, 0x7d, 0x27, 0xeb, 0x08, 0xd9, 0xc6, 0x03, 0xfa, 0x78, 0x9e, 0xe4, 0x05,
	0x4a, 0x40, 0x6e, 0x41, 0xd9, 0x93, 0x22, 0x46, 0x11, 0x1f, 0x8f, 0x03, 0x34, 0x7d, 0x91, 0x0e,
	0xd1, 0xa7, 0x16, 0x6c, 0x3c, 0xe8, 0x63, 0x38, 0x7e, 0xe8, 0x75, 0xd0, 0xcf, 0xaa, 0xd1, 0xee,
	0xcc, 0x10, 0xbc, 0xb1, 0x44, 0xa3, 0xd9, 0x9a, 0x69, 0x89, 0x5e, 0x33, 0x12, 0x5d, 0x85, 0x62,
	0xa4, 0x9e, 0x9b, 0x05, 0x0c, 0xa2, 0x7f, 0x5a, 0x00, 0xfa, 0xc5, 0x23, 0x71, 0x22, 0x13, 0xd5,
	0x58, 0x10, 0xf0, 0xd6, 0x64, 0x46, 0x14, 0x98, 0xea, 0x9b, 0x9b, 0xd5, 0xb7, 0x97, 0xac, 0xaa,
	0x34, 0xb0, 0x1d, 0x0d, 0x92, 0xd1, 0xf0, 0x94, 0xbe, 0x6e, 0xcc, 0x7d, 0x2d, 0x41, 0xde, 0x01,
	0x1d, 0x3a, 0xe6, 0x3e, 0xaa, 0xd9, 0x19, 0x05, 0x3c, 0x34, 0x09, 0x05, 0x9d, 0xa0, 0x43, 0xd3,
	0x84, 0xd4, 0x70, 0x15, 0xe7, 0x87, 0x8b, 0xfe, 0x3e, 0xaf, 0xe1, 0xcb, 0x58, 0xf8, 0x21, 0x94,
	0xb5, 0x00, 0x2e, 0x17, 0x27, 0xd2, 0x74, 0xdf, 0x8d, 0x25, 0xca, 0x9e, 0x69, 0xe3, 0x40, 0x74,
	0xa6, 0xd3, 0x26, 0x54, 0x06, 0x3c, 0xe2, 0xb1, 0x2b, 0x03, 0x14, 0xbc, 0x35, 0xf1, 0x5a, 0xc5,
	0xbe, 0x54, 0x21, 0x7a, 0x0c, 0xeb, 0x9f, 0xf7, 0xfd, 0xe0, 0xdb, 0x11, 0x7b, 0x5e, 0x7f, 0x6a,
	0xfd, 0x72, 0x73, 0xfa, 0xa5, 0x77, 0x9f, 0x5f, 0xd8, 0xfd, 0x5f, 0x39, 0xb8, 0x7c, 0x88, 0x02,
	0x43, 0x16, 0xe3, 0xb9, 0x9a, 0x68, 0x7f, 0xa6, 0x89, 0xde, 0x5c, 0x7a, 0x92, 0xce, 0x95, 0x4d,
	0xf7, 0xd1, 0xdf, 0x93, 0xeb, 0xea, 0x1e, 0x94, 0x1e, 0xf5, 0xfd, 0xc0, 0x1d, 0x8e, 0x98, 0x5a,
	0xa6, 0xbc, 0x53, 0x5b, 0x52, 0xcb, 0xec, 0xdc, 0x59, 0x7f, 0x64, 0x24, 0xb8, 0x06, 0x36, 0x8f,
	0x5c, 0xed, 0xb3, 0xe2, 0x50, 0x72, 0x4a, 0x3c, 0xfa, 0x54, 0xe1, 0xf9, 0xa6, 0xc8, 0x2f, 0x6d,
	0x0a, 0x93, 0x30, 0x99, 0xac, 0xc2, 0x34, 0x61, 0x1c, 0x20, 0xd9, 0x82, 0x4b, 0x26, 0x81, 0x8b,
	0x18, 0xc3, 0x01, 0xeb, 0x9a, 0xd6, 0xda, 0xd0, 0xe1, 0x23, 0x13, 0xa5, 0x6c, 0x51, 0xbe, 0x97,
	0xe9, 0x9f, 0x1a, 0x94, 0x12, 0xe7, 0xbb, 0x5c, 0x9c, 0x1a, 0x93, 0xa6, 0x78, 0xe7, 0x59, 0x11,
	0x5e, 0xd1, 0xc7, 0xcb, 0x43, 0x0c, 0x07, 0xdc, 0x43, 0xf2, 0x93, 0x05, 0xf6, 0xf4, 0x76, 0x25,
	0x37, 0x57, 0x7c, 0x25, 0xd4, 0x56, 0x24, 0x44, 0xf4, 0x83, 0x1f, 0xff, 0xf9, 0xf7, 0x97, 0xdc,
	0x5d, 0xfa, 0x56, 0x63, 0x38, 0x62, 0x8d, 0x36, 0xc6, 0xc3, 0x11, 0x4b, 0x9e, 0x7d, 0x94, 0x6e,
	0x82, 0xfd, 0x1f, 0xd2, 0xe8, 0xf1, 0xae, 0xf2, 0x91, 0xfc, 0x61, 0x01, 0x59, 0xbc, 0x0a, 0xc8,
	0x9d, 0xac, 0x37, 0x6b, 0x2d, 0x6b, 0x66, 0x44, 0x3f, 0x56, 0x2c, 0x77, 0xe9, 0xce, 0x1c, 0xcb,
	0xbe, 0x4e, 0xcd, 0x40, 0xf6, 0x57, 0x0b, 0x2a, 0xe9, 0xe3, 0x9a, 0xd0, 0xd5, 0xf7, 0x43, 0x6d,
	0x75, 0x4e, 0x44, 0x8f, 0x14, 0xb5, 0x03, 0xba, 0xd7, 0xf0, 0xda, 0x7c, 0xbb, 0xc9, 0x45, 0x42,
	0x91, 0x05, 0x41, 0x43, 0x9f, 0x54, 0xc3, 0x11, 0xd3, 0x5f, 0xa0, 0x19, 0x38, 0x3e, 0xb5, 0xa0,
	0x9c, 0x3a, 0x8e, 0xc8, 0xe6, 0xca, 0xe3, 0xb9, 0xb6, 0x32, 0x25, 0xa2, 0xbb, 0x8a, 0xe0, 0xbb,
	0xf4, 0x6d, 0xa5, 0x9d, 0x3a, 0x1b, 0xf4, 0xe9, 0x93, 0x81, 0xd1, 0x33, 0x0b, 0x36, 0x66, 0x7b,
	0x9c, 0xdc, 0xce, 0x32, 0xee, 0xb5, 0x2c, 0x59, 0x11, 0xdd, 0x57, 0xd4, 0xde, 0xa3, 0x0d, 0x63,
	0xab, 0x7e, 0x9e, 0x95, 0xdd, 0xfd, 0xad, 0xef, 0x5f, 0x6f, 0xf3, 0xb8, 0xd3, 0x6f, 0x26, 0xe5,
	0x1b, 0x2d, 0x1c, 0x6c, 0x27, 0x83, 0x93, 0x7c, 0xc8, 0xcf, 0xfe, 0x07, 0x68, 0x16, 0xd5, 0xc7,
	0xfc, 0xdd, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x04, 0x8b, 0x2c, 0x10, 0x1c, 0x0c, 0x00, 0x00,
}
