// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wx-miniprogram/token.proto

package wx_miniprogram // import "github.com/dev-openapi/wx-miniprogram"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetAccessTokenReq struct {
	GrantType            string   `protobuf:"bytes,1,opt,name=grant_type,json=grantType" json:"grant_type,omitempty"`
	Appid                string   `protobuf:"bytes,2,opt,name=appid" json:"appid,omitempty"`
	Secret               string   `protobuf:"bytes,3,opt,name=secret" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccessTokenReq) Reset()         { *m = GetAccessTokenReq{} }
func (m *GetAccessTokenReq) String() string { return proto.CompactTextString(m) }
func (*GetAccessTokenReq) ProtoMessage()    {}
func (*GetAccessTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_d2505d649920eeca, []int{0}
}
func (m *GetAccessTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccessTokenReq.Unmarshal(m, b)
}
func (m *GetAccessTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccessTokenReq.Marshal(b, m, deterministic)
}
func (dst *GetAccessTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccessTokenReq.Merge(dst, src)
}
func (m *GetAccessTokenReq) XXX_Size() int {
	return xxx_messageInfo_GetAccessTokenReq.Size(m)
}
func (m *GetAccessTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccessTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccessTokenReq proto.InternalMessageInfo

func (m *GetAccessTokenReq) GetGrantType() string {
	if m != nil {
		return m.GrantType
	}
	return ""
}

func (m *GetAccessTokenReq) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *GetAccessTokenReq) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type GetAccessTokenRes struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	ExpiresIn            int32    `protobuf:"varint,2,opt,name=expires_in,json=expiresIn" json:"expires_in,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccessTokenRes) Reset()         { *m = GetAccessTokenRes{} }
func (m *GetAccessTokenRes) String() string { return proto.CompactTextString(m) }
func (*GetAccessTokenRes) ProtoMessage()    {}
func (*GetAccessTokenRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_d2505d649920eeca, []int{1}
}
func (m *GetAccessTokenRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccessTokenRes.Unmarshal(m, b)
}
func (m *GetAccessTokenRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccessTokenRes.Marshal(b, m, deterministic)
}
func (dst *GetAccessTokenRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccessTokenRes.Merge(dst, src)
}
func (m *GetAccessTokenRes) XXX_Size() int {
	return xxx_messageInfo_GetAccessTokenRes.Size(m)
}
func (m *GetAccessTokenRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccessTokenRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccessTokenRes proto.InternalMessageInfo

func (m *GetAccessTokenRes) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GetAccessTokenRes) GetExpiresIn() int32 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

func init() {
	proto.RegisterType((*GetAccessTokenReq)(nil), "api.weixin.qq.com.GetAccessTokenReq")
	proto.RegisterType((*GetAccessTokenRes)(nil), "api.weixin.qq.com.GetAccessTokenRes")
}

func init() { proto.RegisterFile("wx-miniprogram/token.proto", fileDescriptor_token_d2505d649920eeca) }

var fileDescriptor_token_d2505d649920eeca = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0xd9, 0x64, 0x83, 0xc5, 0x31, 0x5c, 0x90, 0x31, 0x86, 0x82, 0x16, 0x45, 0x6f, 0x9a,
	0x82, 0x3e, 0x81, 0xde, 0x88, 0xb7, 0x75, 0xde, 0x78, 0x53, 0xd3, 0xec, 0x10, 0x0f, 0xda, 0x24,
	0x4d, 0xe2, 0xd6, 0xdd, 0x8a, 0x6f, 0xe0, 0xa3, 0xf9, 0x0a, 0x3e, 0x88, 0x34, 0x2d, 0xc8, 0xe8,
	0x8d, 0x97, 0xe7, 0xcf, 0x7f, 0xf2, 0xff, 0xf9, 0x42, 0x16, 0x9b, 0x2a, 0x2e, 0x50, 0xa1, 0xb1,
	0x5a, 0x5a, 0x5e, 0x24, 0x5e, 0xbf, 0x82, 0x62, 0xc6, 0x6a, 0xaf, 0xe9, 0x94, 0x1b, 0x64, 0x1b,
	0xc0, 0x0a, 0x15, 0x2b, 0x4b, 0x26, 0x74, 0xb1, 0x38, 0x92, 0x5a, 0xcb, 0x37, 0x48, 0xb8, 0xc1,
	0x84, 0x2b, 0xa5, 0x3d, 0xf7, 0xa8, 0x95, 0x6b, 0x16, 0xa2, 0x67, 0x32, 0xbd, 0x03, 0x7f, 0x23,
	0x04, 0x38, 0xb7, 0xac, 0x2f, 0x4a, 0xa1, 0xa4, 0xc7, 0x84, 0x48, 0xcb, 0x95, 0xcf, 0xfc, 0xd6,
	0xc0, 0xbc, 0x77, 0xd2, 0xbb, 0x1c, 0xa5, 0xa3, 0xa0, 0x2c, 0xb7, 0x06, 0xe8, 0x21, 0x19, 0x70,
	0x63, 0x70, 0x35, 0xef, 0x87, 0x93, 0x66, 0xa0, 0x33, 0x32, 0x74, 0x20, 0x2c, 0xf8, 0xf9, 0x5e,
	0x90, 0xdb, 0x29, 0x7a, 0xec, 0x26, 0x38, 0x7a, 0x4a, 0xc6, 0x3c, 0x28, 0x59, 0x68, 0xdf, 0x66,
	0xec, 0xf3, 0x3f, 0x57, 0x5d, 0x02, 0x2a, 0x83, 0x16, 0x5c, 0x86, 0x2a, 0x44, 0x0d, 0xd2, 0x51,
	0xab, 0xdc, 0xab, 0xab, 0xcf, 0x1e, 0x19, 0x07, 0xe3, 0x03, 0xd8, 0x35, 0x0a, 0xa0, 0x9e, 0x4c,
	0x76, 0x73, 0xe8, 0x19, 0xeb, 0xd0, 0x60, 0x9d, 0xc7, 0x2e, 0xfe, 0xe3, 0x72, 0xd1, 0xec, 0xe3,
	0xfb, 0xe7, 0xab, 0x7f, 0x40, 0x27, 0x89, 0x90, 0x18, 0xe7, 0xa8, 0x1a, 0xec, 0xb7, 0x17, 0x4f,
	0xe7, 0x12, 0xfd, 0xcb, 0x7b, 0x5e, 0xef, 0x25, 0x2b, 0x58, 0xc7, 0xda, 0x80, 0xaa, 0x59, 0xef,
	0xfe, 0x52, 0x3e, 0x0c, 0xbc, 0xaf, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb3, 0xf6, 0x80, 0xfc,
	0xbe, 0x01, 0x00, 0x00,
}
